/* written by klaus degner, ipoque GmbH
 * klaus.degner@ipoque.com
 */

#ifndef __IPOQUE_API_INCLUDE_FILE__
#error CANNOT INCLUDE THIS .H FILE, INCLUDE IPQ_API.H
#endif

#ifndef __IPQ_PROTOCOL_SUBTYPES_H__
#define __IPQ_PROTOCOL_SUBTYPES_H__

#ifdef __cplusplus
extern "C" {
#endif


/* BT protocol subtypes */
#define IPOQUE_PROTOCOL_BITTORRENT_SUBTYPE_PLAIN	0
#define IPOQUE_PROTOCOL_BITTORRENT_SUBTYPE_ENCRYPTED	1
#define IPOQUE_PROTOCOL_BITTORRENT_SUBTYPE_UTP			2
#define IPOQUE_PROTOCOL_BITTORRENT_SUBTYPE_UTP_ENCRYPTED         3

#define IPOQUE_MAX_SUPPORTED_BITTORRENT_SUB_PROTOCOLS	3
#define IPOQUE_PROTOCOL_BITTORRENT_SUBTYPE_STRING "plain","encrypted", "uTP", "uTP_encrypted"


/* Edonkey protocol subtypes */
#define IPOQUE_PROTOCOL_EDONKEY_SUBTYPE_PLAIN		0
#define IPOQUE_PROTOCOL_EDONKEY_SUBTYPE_ENCRYPTED	1


#define IPOQUE_MAX_SUPPORTED_EDONKEY_SUB_PROTOCOLS	1
#define IPOQUE_PROTOCOL_EDONKEY_SUBTYPE_STRING "plain","encrypted"

/* SIP protocol subtypes */
#define IPOQUE_PROTOCOL_SIP_SUBTYPE_UNKNOWN	0
// MSN and YAHOO ARE JUST STUBS, MSN AND YAHOO DETECTION WILL CHANGE THE MARK TO MSN-VOICE OR YAHOO VOICE
#define IPOQUE_PROTOCOL_SIP_SUBTYPE_MSN		1
#define IPOQUE_PROTOCOL_SIP_SUBTYPE_YAHOO	2
#define IPOQUE_PROTOCOL_SIP_SUBTYPE_VONAGE	3
#define IPOQUE_PROTOCOL_SIP_SUBTYPE_OSCAR   4
#define IPOQUE_PROTOCOL_SIP_SUBTYPE_GG      5
#define IPOQUE_PROTOCOL_SIP_SUBTYPE_OSCAR_VIDEO      6
#define IPOQUE_PROTOCOL_SIP_SUBTYPE_YAHOO_VIDEO      7
#define IPOQUE_PROTOCOL_SIP_SUBTYPE_ICHAT_FACETIME		8
#define IPOQUE_PROTOCOL_SIP_SUBTYPE_MAGICJACK		9
#define IPOQUE_PROTOCOL_SIP_SUBTYPE_AUDIO      10
#define IPOQUE_PROTOCOL_SIP_SUBTYPE_VIDEO      11
#define IPOQUE_PROTOCOL_SIP_SUBTYPE_MPLUS      12

#define IPOQUE_MAX_SUPPORTED_SIP_SUB_PROTOCOLS 12
#define IPOQUE_PROTOCOL_SIP_SUBTYPE_STRING "unknown","msn","yahoo","vonage","oscar","gadu-gadu","oscar-video", "yahoo-video", "ichat-facetime", "magicjack", "audio", "video", "mplus"

/* MSN SUBTYPES */
#define	IPOQUE_PROTOCOL_MSN_SUBTYPE_UNKNOWN		0
#define	IPOQUE_PROTOCOL_MSN_SUBTYPE_AUDIO		1
#define	IPOQUE_PROTOCOL_MSN_SUBTYPE_FILETRANSFER	2
#define	IPOQUE_PROTOCOL_MSN_SUBTYPE_VIDEO		3
#define	IPOQUE_PROTOCOL_MSN_SUBTYPE_WEBCHAT		4

#define IPOQUE_MAX_SUPPORTED_MSN_SUB_PROTOCOLS		4
#define IPOQUE_PROTOCOL_MSN_SUBTYPE_STRING "unknown","voice","file-transfer","video","webchat"

/* YAHOO SUBTYPES */
#define	IPOQUE_PROTOCOL_YAHOO_SUBTYPE_UNKNOWN		0
#define	IPOQUE_PROTOCOL_YAHOO_SUBTYPE_AUDIO			1
#define	IPOQUE_PROTOCOL_YAHOO_SUBTYPE_FILETRANSFER	2
#define	IPOQUE_PROTOCOL_YAHOO_SUBTYPE_VIDEO			3
#define	IPOQUE_PROTOCOL_YAHOO_SUBTYPE_WEBCHAT		4
#define IPOQUE_PROTOCOL_YAHOO_SUBTYPE_WEBMAIL		5

#define IPOQUE_MAX_SUPPORTED_YAHOO_SUB_PROTOCOLS	5
#define IPOQUE_PROTOCOL_YAHOO_SUBTYPE_STRING "unknown","voice","file-transfer","video","webchat","webmail"

/* OSCAR SUBTYPES */
#define	IPOQUE_PROTOCOL_OSCAR_SUBTYPE_UNKNOWN		0
#define	IPOQUE_PROTOCOL_OSCAR_SUBTYPE_FILETRANSFER	1
#define IPOQUE_PROTOCOL_OSCAR_SUBTYPE_PICTURETRANSFER   2
#define IPOQUE_PROTOCOL_OSCAR_SUBTYPE_AUDIO             3
#define IPOQUE_PROTOCOL_OSCAR_SUBTYPE_VIDEO             4

#define IPOQUE_MAX_SUPPORTED_OSCAR_SUB_PROTOCOLS        4
#define IPOQUE_PROTOCOL_OSCAR_SUBTYPE_STRING "unknown","file-transfer","picture-transfer","voice","video"

/* IRC SUBTYPES */
#define	IPOQUE_PROTOCOL_IRC_SUBTYPE_UNKNOWN		0
#define	IPOQUE_PROTOCOL_IRC_SUBTYPE_FILETRANSFER	1

#define IPOQUE_MAX_SUPPORTED_IRC_SUB_PROTOCOLS		1
#define IPOQUE_PROTOCOL_IRC_SUBTYPE_STRING "unknown","file-transfer"

/* GADU-GADU SUBTYPES */
#define IPOQUE_PROTOCOL_GG_SUBTYPE_SERVER                               0
#define IPOQUE_PROTOCOL_GG_SUBTYPE_FILETRANSFER                         1
#define IPOQUE_PROTOCOL_GG_SUBTYPE_AUDIO                                2
#define IPOQUE_PROTOCOL_GG_SUBTYPE_VIDEO                                3

#define IPOQUE_MAX_SUPPORTED_GG_SUB_PROTOCOLS                           3
#define IPOQUE_PROTOCOL_GG_SUBTYPE_STRING "server","file-transfer","voice","video"

/* GTP SUBTYPES */
#define IPOQUE_PROTOCOL_GTP_SUBTYPE_GTPC		0
#define IPOQUE_PROTOCOL_GTP_SUBTYPE_GTPU		1
#define IPOQUE_PROTOCOL_GTP_SUBTYPE_PRIME		2

#define IPOQUE_MAX_SUPPORTED_GTP_SUB_PROTOCOLS		2
#define IPOQUE_PROTOCOL_GTP_SUBTYPE_STRING "control","user-data","prime"

/*Directconnect Subtypes */
#define IPOQUE_PROTOCOL_DIRECTCONNECT_SUBTYPE_HUB       0
#define IPOQUE_PROTOCOL_DIRECTCONNECT_SUBTYPE_PEER      1
#define IPOQUE_PROTOCOL_DIRECTCONNECT_SUBTYPE_ADC_PEER  2

#define IPOQUE_MAX_SUPPORTED_DIRECTCONNECT_SUB_PROTOCOLS		2
#define IPOQUE_PROTOCOL_DIRECTCONNECT_SUBTYPE_STRING "hub","peer","adc-peer"

/*Paltalk Subtypes */
#define IPOQUE_PROTOCOL_PALTALK_SUBTYPE_SERVER       		0
#define IPOQUE_PROTOCOL_PALTALK_SUBTYPE_FT      		1
#define IPOQUE_PROTOCOL_PALTALK_SUBTYPE_VOICE      		2
#define IPOQUE_PROTOCOL_PALTALK_SUBTYPE_VIDEO      		3
#define IPOQUE_MAX_SUPPORTED_PALTALK_SUB_PROTOCOLS		3
#define IPOQUE_PROTOCOL_PALTALK_SUBTYPE_STRING "server","file-transfer","voice","video"

/* skype voice types */
#define	IPOQUE_PROTOCOL_SKYPE_SUBTYPE_UNKNOWN	0
#define	IPOQUE_PROTOCOL_SKYPE_SUBTYPE_AUDIO	1
#define	IPOQUE_PROTOCOL_SKYPE_SUBTYPE_SKYPEOUT	2
#define	IPOQUE_PROTOCOL_SKYPE_SUBTYPE_VIDEO	3
#define	IPOQUE_PROTOCOL_SKYPE_SUBTYPE_CHAT	4
#define	IPOQUE_PROTOCOL_SKYPE_SUBTYPE_FILETRANSFER	5
#define IPOQUE_MAX_SUPPORTED_SKYPE_SUB_PROTOCOLS	5
#define IPOQUE_PROTOCOL_SKYPE_SUBTYPE_STRING "unknown","voice","out","video", "chat", "file-transfer"

#define IPOQUE_PROTOCOL_FTP_SUBTYPE_CONTROL 0
#define IPOQUE_PROTOCOL_FTP_SUBTYPE_DATA 1
#define IPOQUE_MAX_SUPPORTED_FTP_SUB_PROTOCOLS	1
#define IPOQUE_PROTOCOL_FTP_SUBTYPE_STRING "control","data"

/* jabber subtypes */
#define	IPOQUE_PROTOCOL_JABBER_SUBTYPE_UNKNOWN		0
#define	IPOQUE_PROTOCOL_JABBER_SUBTYPE_AUDIO		1
#define	IPOQUE_PROTOCOL_JABBER_SUBTYPE_FT   		2
#define	IPOQUE_PROTOCOL_JABBER_SUBTYPE_VIDEO   		3
#define IPOQUE_PROTOCOL_JABBER_SUBTYPE_ENCRYPTED    4

#define IPOQUE_MAX_SUPPORTED_JABBER_SUB_PROTOCOLS	4
#define IPOQUE_PROTOCOL_JABBER_SUBTYPE_STRING "unknown","voice","file-transfer","video","encrypted"

/* truphone subtypes, truphone must have subtypes, because it is integrated in jabber.*/
#define IPOQUE_PROTOCOL_TRUPHONE_SUBTYPE_UNKNOWN	0

#define IPOQUE_MAX_SUPPORTED_TRUPHON_SUB_PROTOCOLS	0
#define IPOQUE_PROTOCOL_TRUPHONE_SUBTYPE_STRING "unknown"

/* qq subtypes */
#define	IPOQUE_PROTOCOL_QQ_SUBTYPE_UNKNOWN		0
#define	IPOQUE_PROTOCOL_QQ_SUBTYPE_AUDIO		1
#define	IPOQUE_PROTOCOL_QQ_SUBTYPE_FT   		2
#define	IPOQUE_PROTOCOL_QQ_SUBTYPE_VIDEO   		3

#define IPOQUE_MAX_SUPPORTED_QQ_SUB_PROTOCOLS	3
#define IPOQUE_PROTOCOL_QQ_SUBTYPE_STRING "unknown","voice","file-transfer","video"

/* meebo subtypes */
#define IPOQUE_PROTOCOL_MEEBO_SUBTYPE_UNKNOWN       0
#define IPOQUE_PROTOCOL_MEEBO_SUBTYPE_AUDIO         1
#define IPOQUE_PROTOCOL_MEEBO_SUBTYPE_VIDEO         2

#define IPOQUE_MAX_SUPPORTED_MEEBO_SUB_PROTOCOLS    2
#define IPOQUE_PROTOCOL_MEEBO_SUBTYPE_STRING "unknown","audio","video"

/* Blackberry subtypes */
#define IPOQUE_PROTOCOL_BLACKBERRY_SUBTYPE_UNKNOWN		0
#define IPOQUE_PROTOCOL_BLACKBERRY_SUBTYPE_ENCRYPTED	1
#define IPOQUE_PROTOCOL_BLACKBERRY_SUBTYPE_EMAIL		2
#define IPOQUE_PROTOCOL_BLACKBERRY_SUBTYPE_MESSENGER	3

#define IPOQUE_MAX_SUPPORTED_BLACKBERRY_SUB_PROTOCOLS	3
#define IPOQUE_PROTOCOL_BLACKBERRY_SUBTYPE_STRING "unknown","encrypted","email","messenger"

/* MyPeople subtypes */
#define IPOQUE_PROTOCOL_MYPEOPLE_SUBTYPE_UNKNOWN		0
#define IPOQUE_PROTOCOL_MYPEOPLE_SUBTYPE_AUDIO			1

#define IPOQUE_MAX_SUPPORTED_MYPEOPLE_SUB_PROTOCOLS		1
#define IPOQUE_PROTOCOL_MYPEOPLE_SUBTYPE_STRING "unknown","audio"

/* Viber subtypes */
#define IPOQUE_PROTOCOL_VIBER_SUBTYPE_UNKNOWN		0
#define IPOQUE_PROTOCOL_VIBER_SUBTYPE_AUDIO			1
#define IPOQUE_PROTOCOL_VIBER_SUBTYPE_IM			2
#define IPOQUE_PROTOCOL_VIBER_SUBTYPE_FT            3
#define IPOQUE_PROTOCOL_VIBER_SUBTYPE_OUT           4

#define IPOQUE_MAX_SUPPORTED_VIBER_SUB_PROTOCOLS    4
#define IPOQUE_PROTOCOL_VIBER_SUBTYPE_STRING "unknown","audio","im","file-transfer", "out"

/* Lync subtypes */
#define IPOQUE_PROTOCOL_LYNC_SUBTYPE_UNKNOWN		0
#define IPOQUE_PROTOCOL_LYNC_SUBTYPE_AUDIO			1
#define IPOQUE_PROTOCOL_LYNC_SUBTYPE_VIDEO			2
#define IPOQUE_PROTOCOL_LYNC_SUBTYPE_FT				3

#define IPOQUE_MAX_SUPPORTED_LYNC_SUB_PROTOCOLS    3
#define IPOQUE_PROTOCOL_LYNC_SUBTYPE_STRING "unknown","audio","video","filetransfer"

/* HTTP subtypes */
#define IPOQUE_PROTOCOL_HTTP_SUBTYPE_GENERIC		0
#define IPOQUE_PROTOCOL_HTTP_SUBTYPE_AUDIO			1
#define IPOQUE_PROTOCOL_HTTP_SUBTYPE_VIDEO			2
#define IPOQUE_PROTOCOL_HTTP_SUBTYPE_MEDIA			3

#define IPOQUE_MAX_SUPPORTED_HTTP_SUB_PROTOCOLS     3
#define IPOQUE_PROTOCOL_HTTP_SUBTYPE_STRING "generic","audio","video","media"

/* DDL protocol subtypes */
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_4SHARED_COM		0
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_ADRIVE_COM		1
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_BADONGO_COM		2
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_BADONGO_NET		3
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_BESTSHARING_COM		4
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_BIGFILEZ_COM		5
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_CHINAMOFILE_COM		6
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_DATA_HU		7
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_DEPOSITFILES_COM		8
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_EASY_SHARE_COM		9
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FAST_LOAD_NET		10
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FAST_SHARE_COM		11
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILE_UPLOAD_NET		12
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILE_UPLOAD_TO		13
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILEARCHIV_RU		14
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILEBASE_TO		15
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILECLOUD_COM		16
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILEFACTORY_COM		17
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILEFRONT_COM		18
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILEHO_COM		19
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILEHOST_TV		20
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILEPOST_RU		21
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILER_NET		22
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILES_UPLOAD_COM		23
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILES_TO		24
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILESAFE_TO		25
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILESEND_NET		26
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILEUPYOURS_COM		27
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FTP2SHARE_COM		28
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_GIGASIZE_COM		29
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_GIGESHARE_COM		30
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_HOSTGGG_COM		31
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_HOTFILE_COM		32
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_IFOLDER_RU		33
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_KEEPMYFILE_COM		34
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_LETECKAPOSTA_CZ		35
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_LIVE_SHARE_COM		36
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_LIVEDEPOT_NET		37
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_LOAD_TO		38
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_MASSMIRROR_COM		39
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_MEDIAFIRE_COM		40
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_MEGAROTIC_COM		41
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_MEGASHARE_COM		42
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_MEGASHARES_COM		43
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_MEGAUPLOAD_COM		44
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_MOFILE_COM		45
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_MOFILE_NET		46
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_MYTEMPDIR_COM		47
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_NETLOAD_IN		48
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_ODSIEBIE_NAJLEPSZE_NET		49
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_QUICKSHARING_COM		50
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_RAPIDSHARE_COM		51
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_RAPIDSHARE_DE		52
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_RAPIDUPLOAD_COM		53
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_SAVEFILE_COM		54
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_SENDMEFILE_COM		55
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_SENDSPACE_COM		56
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_SHAREBASE_TO		57
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_SHAREBEE_COM		58
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_SHAREBIG_COM		59
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_SHAREBIGFILE_COM		60
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_SHAREBIGFLIE_COM		61
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_SIMPLEUPLOAD_NET		62
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_SPEEDSHARE_ORG		63
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_TURBOUPLOAD_COM		64
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_ULTRASHARE_DE		65
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_UP_FILE_COM		66
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_UPLOADED_TO		67
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_UPLOADING_COM		68
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_UPLOADINGIT_COM		69
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_UPLOADPOWER_COM		70
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_UPLOADYOURFILES_DE		71
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_VIP_FILE_COM		72
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_WIIUPLOAD_NET		73
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_YOURFILEHOST_COM		74
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_YOURFILES_BIZ		75
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_YOUTUBE_COM		76
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_ZSHARE_NET		77
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_4SHARED_VN		78
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_MEGA_1280_COM		79
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_MEGASHARE_VN		80
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILESERVE_COM		81
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILESONIC_COM		82
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_1_UPLOAD_TO		83
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_1FICHIER_COM		84
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_4FASTFILE_COM		85
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_10UPLOAD_COM		86
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_1CLICKSHARE_NET		87
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILEDUDE_COM		88
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_ASIXFILES_COM		89
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_BANASHARE_COM		90
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_BIGGERUPLOAD_COM		91
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_BITSHARE_COM		92
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_CASH_FILE_NET		93
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_CRAMIT_IN		94
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_CZSHARE_COM		95
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_DATA_LOADING_COM		96
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_DATAPORT_CZ		97
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_DATEI_TO		98
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_DOWNUPLOAD_COM		99
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_EASYBYTEZ_COM		100
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_EDISK_CZ		101
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_ENTERUPLOAD_COM		102
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_EUROSHARE_EU		103
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_EXTABIT_COM		104
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FASTFILESHARE_COM_AR		105
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FIK1_COM		106
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILE2UPLOAD_NET		107
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILEAPE_COM		108
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILEFLYER_COM		109
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILEFROG_COM		110
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILEHOOK_COM		111
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILEOVER_NET		112
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILEPOST_COM		113
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILES_MAIL_RU		114
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILESHARE_IN_UA		115
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILESMONSTER_COM		116
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILEVO_COM		117
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILEZUP_COM		118
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FREAKSHARE_NET		119
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FSHARE_VN		120
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_GAIAFILE_COM		121
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_GIGAPETA_COM		122
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_GOTOUPLOAD_COM		123
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_HELLSHARE_COM		124
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_HITFILE_NET		125
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_HULKSHARE_COM		126
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_HYPERFILESHARE_COM		127
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_I_FILEZ_COM		128
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_IFILE_IT		129
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_KEWLSHARE_COM		130
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_LETITBIT_NET		131
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_LOADFILES_IN		132
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_MEGAFREE_KZ		133
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_MEGARAPID_EU		134
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_MEGASHARE_VNN_VN		135
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_MIDUPLOAD_COM		136
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_MULTISHARE_CZ		137
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_NETUPLOADED_COM		138
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_ORON_COM		139
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_PRZEKLEJ_PL		140
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_PUTSHARE_COM		141
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_QSHARE_COM		142
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_QUICKSHARE_CZ		143
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_RAPIDSHARK_PL		144
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_SCRIBD_COM		145
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_SHARE_ONLINE_BZ		146
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_SHARE_RAPID_CZ		147
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_SHRAGLE_COM		148
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_STORAGE_TO		149
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_TERAFILES_NET		150
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_TUNABOX_NET		151
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_TURBOBIT_NET		152
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_UGOTFILE_COM		153
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_ULOZ_TO		154
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_UNIBYTES_COM		155
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_UNLIMIT_CO_IL		156
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_UP_4SHARE_VN		157
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_UPLOAD_COM_UA		158
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_UPLOADBOX_COM		159
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_UPLOADER_PL		160
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_UPLOADFLOOR_COM		161
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_UPLOADSTATION_COM		162
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_UPNITO_SK		163
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_USERSHARE_NET		164
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_VIDEOBB_COM		165
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_WUPLOAD_COM		166
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_X7_TO		167
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_YUNFILE_TO		168
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_ZOMGUPLOAD_TO		169
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_ZIDDU_COM		170
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_1_UPLOAD_COM		171
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_1_CLICKSHARE_COM		172
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_123UPLOAD_PL		173
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_139PAN_COM		174
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_163PAN_COM		175
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_2SHARED_COM		176
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_4SHARE_WS		177
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_4US_TO		178
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_ALLDRIVES_GE		179
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_ALLSHARES_GE		180
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_ANNONHOST_NET		181
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_BOOSTERKING_COM		182
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_COBRASHARE_SK		183
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_COOLSHARE_CZ		184
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_CROCKO_COM		185
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_CUM_COM		186
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_EYVX_COM		187
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILEARN_COM		188
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILEJUNGLE_COM		189
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILEMAZE_WS		190
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILESFLASH_COM		191
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FREESPACE_BY		192
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FSX_HU		193
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_JAKFILE_COM		194
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_JUMBOFILES_COM		195
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_KICKLOAD_COM		196
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_MISSUPLOAD_COM		197
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_MOVREEL_COM		198
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_PLATINSHARE_COM		199
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_SANUPLOAD_COM		200
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_SHAREFLARE_NET		201
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_U_115_COM		202
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_UPLOADC_COM		203
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_UPLOADKING_COM		204
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_UPTOBOX_COM		205
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILESTUBE_COM		206
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_GAMEFRONT_COM		207
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_MEGAPORN_COM		208
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_FILESONIC_IN		209
#define IPOQUE_PROTOCOL_DDL_SUBTYPE_TURBOBIT_RU		210
#define IPOQUE_PROTOCOL_DIRECT_DOWNLOAD_LINK_SUBTYPE_STRING "4shared.com", \
	"adrive.com", "badongo.com", "badongo.net", "bestsharing.com", "bigfilez.com", "chinamofile.com", "data.hu", "depositfiles.com", \
	"easy-share.com", "fast-load.net", "fast-share.com", "file-upload.net", "file-upload.to", "filearchiv.ru", "filebase.to", "filecloud.com", \
	"filefactory.com", "filefront.com", "fileho.com", "filehost.tv", "filepost.ru", "filer.net", "files-upload.com", "files.to", \
	"filesafe.to", "filesend.net", "fileupyours.com", "ftp2share.com", "gigasize.com", "gigeshare.com", "hostggg.com", "hotfile.com", \
	"ifolder.ru", "keepmyfile.com", "leteckaposta.cz", "live-share.com", "livedepot.net", "load.to", "massmirror.com", "mediafire.com", \
	"megarotic.com", "megashare.com", "megashares.com", "megaupload.com", "mofile.com", "mofile.net", "mytempdir.com", "netload.in", \
	"odsiebie.najlepsze.net", "quicksharing.com", "rapidshare.com", "rapidshare.de", "rapidupload.com", "savefile.com", "sendmefile.com", "sendspace.com", \
	"sharebase.to", "sharebee.com", "sharebig.com", "sharebigfile.com", "sharebigflie.com", "simpleupload.net", "speedshare.org", "turboupload.com", \
	"ultrashare.de", "up-file.com", "uploaded.to", "uploading.com", "uploadingit.com", "uploadpower.com", "uploadyourfiles.de", "vip-file.com", \
	"wiiupload.net", "yourfilehost.com", "yourfiles.biz", "youtube.com", "zshare.net", "4shared.vn", "mega.1280.com", "megashare.vn", \
	"fileserve.com", "filesonic.com", "1-upload.to", "1fichier.com", "4fastfile.com", "10upload.com", "1clickshare.net", "filedude.com", \
	"asixfiles.com", "banashare.com", "biggerupload.com", "bitshare.com", "cash-file.net", "cramit.in", "czshare.com", "data-loading.com", \
	"dataport.cz", "datei.to", "downupload.com", "easybytez.com", "edisk.cz", "enterupload.com", "euroshare.eu", "extabit.com", \
	"fastfileshare.com.ar", "fik1.com", "file2upload.net", "fileape.com", "fileflyer.com", "filefrog.com", "filehook.com", "fileover.net", \
	"filepost.com", "files.mail.ru", "fileshare.in.ua", "filesmonster.com", "filevo.com", "filezup.com", "freakshare.net", "fshare.vn", \
	"gaiafile.com", "gigapeta.com", "gotoupload.com", "hellshare.com", "hitfile.net", "hulkshare.com", "hyperfileshare.com", "i-filez.com", \
	"ifile.it", "kewlshare.com", "letitbit.net", "loadfiles.in", "megafree.kz", "megarapid.eu", "megashare.vnn.vn", "midupload.com", \
	"multishare.cz", "netuploaded.com", "oron.com", "przeklej.pl", "putshare.com", "qshare.com", "quickshare.cz", "rapidshark.pl", \
	"scribd.com", "share-online.bz", "share-rapid.cz", "shragle.com", "storage.to", "terafiles.net", "tunabox.net", "turbobit.net", \
	"ugotfile.com", "uloz.to", "unibytes.com", "unlimit.co.il", "up.4share.vn", "upload.com.ua", "uploadbox.com", "uploader.pl", \
	"uploadfloor.com", "uploadstation.com", "upnito.sk", "usershare.net", "videobb.com", "wupload.com", "x7.to", "yunfile.to", \
	"zomgupload.to", "ziddu.com", "1-upload.com", "1-clickshare.com", "123upload.pl", "139pan.com", "163pan.com", "2shared.com", \
	"4share.ws", "4us.to", "alldrives.ge", "allshares.ge", "annonhost.net", "boosterking.com", "cobrashare.sk", "coolshare.cz", \
	"crocko.com", "cum.com", "eyvx.com", "filearn.com", "filejungle.com", "filemaze.ws", "filesflash.com", "freespace.by", \
	"fsx.hu", "jakfile.com", "jumbofiles.com", "kickload.com", "missupload.com", "movreel.com", "platinshare.com", "sanupload.com", \
	"shareflare.net", "u.115.com", "uploadc.com", "uploadking.com", "uptobox.com", "filestube.com", "gamefront.com", "megaporn.com", \
	"filesonic.in", "turbobit.ru"


#ifdef IPOQUE_USE_PRX_PROTOCOLS_ONLY
#define IPOQUE_MAX_SUPPORTED_DIRECT_DOWNLOAD_LINK_SUB_PROTOCOLS		-1
#else
#define IPOQUE_MAX_SUPPORTED_DIRECT_DOWNLOAD_LINK_SUB_PROTOCOLS		210
#endif






/* ORB subtypes */
#define IPOQUE_PROTOCOL_ORB_SUBTYPE_UNKNOWN				0
#define IPOQUE_PROTOCOL_ORB_SUBTYPE_SETUP_SERVER_CONNECTION		1
#define IPOQUE_PROTOCOL_ORB_SUBTYPE_SETUP_CLIENT_CONNECTION		2
#define IPOQUE_PROTOCOL_ORB_SUBTYPE_RTSP_CONNECTION			3
#define IPOQUE_PROTOCOL_ORB_SUBTYPE_RDT_CONNECTION			4
#define IPOQUE_PROTOCOL_ORB_SUBTYPE_WMV_CONNECTION			5
#define IPOQUE_PROTOCOL_ORB_SUBTYPE_WMA_CONNECTION			6
#define IPOQUE_PROTOCOL_ORB_SUBTYPE_FLASH_CONNECTION			7
#define IPOQUE_PROTOCOL_ORB_SUBTYPE_FLV_CONNECTION			8
#define IPOQUE_PROTOCOL_ORB_SUBTYPE_3GP_CONNECTION			9
#define IPOQUE_PROTOCOL_ORB_SUBTYPE_UPLOAD_DOWNLOAD                    10
#define IPOQUE_PROTOCOL_ORB_SUBTYPE_RTP_CONNECTION			11

#define IPOQUE_PROTOCOL_ORB_SUBTYPE_STRING "unknown","server","client","client-rtsp","client-rdt","client-wmv",\
	"client-wma","client-flash","client-flv","client-3gp","client-upload-download", "client-rtp"

#define IPOQUE_MAX_SUPPORTED_ORB_SUB_PROTOCOLS 11

/* MGCP subtypes */
#define IPOQUE_PROTOCOL_MGCP_SUBTYPE_CONTROL_CONNECTION			0
#define IPOQUE_PROTOCOL_MGCP_SUBTYPE_RTP_CONNECTION			1

#define IPOQUE_PROTOCOL_MGCP_SUBTYPE_STRING "control","rtp"

#define IPOQUE_MAX_SUPPORTED_MGCP_SUB_PROTOCOLS	1

/* IPSEC subtypes */
#define IPOQUE_PROTOCOL_IPSEC_SUBTYPE_PAYLOAD_CONNECTION                 0
#define IPOQUE_PROTOCOL_IPSEC_SUBTYPE_ISAKMP_CONNECTION                  1

#define IPOQUE_PROTOCOL_IPSEC_SUBTYPE_STRING "data","control"

#define IPOQUE_MAX_SUPPORTED_IPSEC_SUB_PROTOCOLS 1

/* gTalk subtypes */
#define IPOQUE_PROTOCOL_HTTP_APPLICATION_GOOGLE_TALK_SUBTYPE_UNKNOWN                             0
#define IPOQUE_PROTOCOL_HTTP_APPLICATION_GOOGLE_TALK_SUBTYPE_AUDIO			         1
#define IPOQUE_PROTOCOL_HTTP_APPLICATION_GOOGLE_TALK_SUBTYPE_FILETRANSFER        		 2
#define IPOQUE_PROTOCOL_HTTP_APPLICATION_GOOGLE_TALK_SUBTYPE_VIDEO                               3

#define IPOQUE_PROTOCOL_HTTP_APPLICATION_GOOGLE_TALK_SUBTYPE_STRING "unknown","voice","file-transfer","video"

#define IPOQUE_MAX_SUPPORTED_HTTP_APPLICATION_GOOGLE_TALK_SUB_PROTOCOLS                         3

/* FRING subtypes */
#define IPOQUE_PROTOCOL_FRING_SUBTYPE_UNKNOWN                            0
#define IPOQUE_PROTOCOL_FRING_SUBTYPE_AUDIO			                     1
#define IPOQUE_PROTOCOL_FRING_SUBTYPE_VIDEO			                     2

#define IPOQUE_PROTOCOL_FRING_SUBTYPE_STRING "unknown","voice","video"

#define IPOQUE_MAX_SUPPORTED_FRING_SUB_PROTOCOLS                         2


/* VEOH subtypes */
#define IPOQUE_PROTOCOL_VEOH_SUBTYPE_GENERIC    0
#define IPOQUE_PROTOCOL_VEOH_SUBTYPE_FLASH      1
#define IPOQUE_PROTOCOL_VEOH_SUBTYPE_STRING "generic", "flash"
#define IPOQUE_MAX_SUPPORTED_VEOH_SUB_PROTOCOLS 1

#define IPOQUE_PROTOCOL_SOCKS_SUBTYPE_V4    0
#define IPOQUE_PROTOCOL_SOCKS_SUBTYPE_V5    1
#define IPOQUE_PROTOCOL_SOCKS_SUBTYPE_STRING "socksv4", "socksv5"
#define IPOQUE_MAX_SUPPORTED_SOCKS_SUB_PROTOCOLS 1

/* tango subtypes */
#define IPOQUE_PROTOCOL_TANGO_SUBTYPE_UNKNOWN                            0
#define IPOQUE_PROTOCOL_TANGO_SUBTYPE_AUDIO			                     1
#define IPOQUE_PROTOCOL_TANGO_SUBTYPE_VIDEO			                     2
#define IPOQUE_PROTOCOL_TANGO_SUBTYPE_IM                                 3
#define IPOQUE_PROTOCOL_TANGO_SUBTYPE_FILETRANSFER                       4
#define IPOQUE_PROTOCOL_TANGO_SUBTYPE_STRING "unknown","audio", "video", "im", "file-transfer"
#define IPOQUE_MAX_SUPPORTED_TANGO_SUB_PROTOCOLS                         4

#define IPOQUE_PROTOCOL_SPDY_SUBTYPE_SSL                            	 0
#define IPOQUE_PROTOCOL_SPDY_SUBTYPE_STRING "ssl"
#define IPOQUE_MAX_SUPPORTED_SPDY_SUB_PROTOCOLS                         0

/* google subtypes */
#define IPOQUE_PROTOCOL_GOOGLE_SUBTYPE_ENCRYPTED	                  	  0
#define IPOQUE_PROTOCOL_GOOGLE_SUBTYPE_CLOUD                              1
#define IPOQUE_PROTOCOL_GOOGLE_SUBTYPE_DRIVE                              2
#define IPOQUE_PROTOCOL_GOOGLE_SUBTYPE_DOCS                               3
#define IPOQUE_PROTOCOL_GOOGLE_SUBTYPE_PLUS                               4
#define IPOQUE_PROTOCOL_GOOGLE_SUBTYPE_PLAY                               5
#define IPOQUE_PROTOCOL_GOOGLE_SUBTYPE_STRING "encrypted", "cloud", "drive", "docs", "plus", "play"
#define IPOQUE_MAX_SUPPORTED_GOOGLE_SUB_PROTOCOLS                         5

/* SSL subtypes */
#define IPOQUE_PROTOCOL_SSL_SUBTYPE_GENERIC                            	 0
#define IPOQUE_PROTOCOL_SSL_SUBTYPE_SPDY                            	 1
#define IPOQUE_PROTOCOL_SSL_SUBTYPE_STRING "generic", "spdy"
#define IPOQUE_MAX_SUPPORTED_SSL_SUB_PROTOCOLS                           1

/* ITV subtypes */
#define IPOQUE_PROTOCOL_ITV_SUBTYPE_WEB	                            	 0
#define IPOQUE_PROTOCOL_ITV_SUBTYPE_STREAM                            	 1
#define IPOQUE_PROTOCOL_ITV_SUBTYPE_STRING "web", "stream"
#define IPOQUE_MAX_SUPPORTED_ITV_SUB_PROTOCOLS                           1

/* DEMAND5 subtypes */
#define IPOQUE_PROTOCOL_DEMAND5_SUBTYPE_WEB	                         0
#define IPOQUE_PROTOCOL_DEMAND5_SUBTYPE_STREAM                          1
#define IPOQUE_PROTOCOL_DEMAND5_SUBTYPE_STRING "web", "stream"
#define IPOQUE_MAX_SUPPORTED_DEMAND5_SUB_PROTOCOLS                      1

/* WeChat subtypes */
#define IPOQUE_PROTOCOL_WECHAT_SUBTYPE_GENERIC                          0
#define IPOQUE_PROTOCOL_WECHAT_SUBTYPE_VOICE_LIVE_CHAT                  1
#define IPOQUE_PROTOCOL_WECHAT_SUBTYPE_VIDEO_CALL                       2
#define IPOQUE_PROTOCOL_WECHAT_SUBTYPE_CHAT                             3
#define IPOQUE_PROTOCOL_WECHAT_SUBTYPE_DATA_MESSAGE                     4
#define IPOQUE_PROTOCOL_WECHAT_SUBTYPE_WEB_CHAT                         5
#define IPOQUE_PROTOCOL_WECHAT_SUBTYPE_STRING "generic", "voice_live_chat", "video_call", "chat", "data_message", "web_chat"
#define IPOQUE_MAX_SUPPORTED_WECHAT_SUB_PROTOCOLS                       5

/* MyVideo subtypes */
#define IPOQUE_PROTOCOL_MYVIDEO_SUBTYPE_WEB	                            0
#define IPOQUE_PROTOCOL_MYVIDEO_SUBTYPE_STREAM                          1
#define IPOQUE_PROTOCOL_MYVIDEO_SUBTYPE_STRING "web", "stream"
#define IPOQUE_MAX_SUPPORTED_MYVIDEO_SUB_PROTOCOLS                      1

/* OTA subtypes */
#define IPOQUE_PROTOCOL_OS_UPDATE_SUBTYPE_ANDROID                       0
#define IPOQUE_PROTOCOL_OS_UPDATE_SUBTYPE_IOS                           1
#define IPOQUE_PROTOCOL_OS_UPDATE_SUBTYPE_WINDOWS_PHONE                 2
#define IPOQUE_PROTOCOL_OS_UPDATE_SUBTYPE_STRING "android", "ios", "windows_phone"
#define IPOQUE_MAX_SUPPORTED_OS_UPDATE_SUB_PROTOCOLS                    2

/* DiDi subtypes */
#define IPOQUE_PROTOCOL_DIDI_SUBTYPE_GENERIC                            0
#define IPOQUE_PROTOCOL_DIDI_SUBTYPE_VOICE                              1
#define IPOQUE_PROTOCOL_DIDI_SUBTYPE_IM                                 2
#define IPOQUE_PROTOCOL_DIDI_SUBTYPE_STRING "generic", "voice", "im"
#define IPOQUE_MAX_SUPPORTED_DIDI_SUB_PROTOCOLS                         2


/* Telnet subtypes */
#define IPOQUE_PROTOCOL_TELNET_SUBTYPE_GENERIC                               0
#define IPOQUE_PROTOCOL_TELNET_SUBTYPE_TN3270                                1
#define IPOQUE_PROTOCOL_TELNET_SUBTYPE_STRING "generic", "tn3270"
#define IPOQUE_MAX_SUPPORTED_TELNET_SUB_PROTOCOLS                      1

/* Microsoft Exchange subtypes */
#define IPOQUE_PROTOCOL_MSEXCHANGE_SUBTYPE_GENERIC                     0
#define IPOQUE_PROTOCOL_MSEXCHANGE_SUBTYPE_OWA                         1
#define IPOQUE_PROTOCOL_MSEXCHANGE_SUBTYPE_STRING "generic", "outlook_web_access"
#define IPOQUE_MAX_SUPPORTED_MSEXCHANGE_SUB_PROTOCOLS                  1

/* PPLive subtypes */
#define IPOQUE_PROTOCOL_PPLIVE_SUBTYPE_GENERIC              0
#define IPOQUE_PROTOCOL_PPLIVE_SUBTYPE_VIDEO                1
#define IPOQUE_PROTOCOL_PPLIVE_SUBTYPE_STRING "generic","video"
#define IPOQUE_MAX_SUPPORTED_PPLIVE_SUB_PROTOCOLS           1

/* Kakaotalk subtypes */
#define IPOQUE_PROTOCOL_KAKAO_SUBTYPE_GENERIC                           0
#define IPOQUE_PROTOCOL_KAKAO_SUBTYPE_KAKAOTALK                         1
#define IPOQUE_PROTOCOL_KAKAO_SUBTYPE_STRING "generic", "kakaotalk"
#define IPOQUE_MAX_SUPPORTED_KAKAO_SUB_PROTOCOLS                        1

/* Line subtypes */
#define IPOQUE_PROTOCOL_LINE_SUBTYPE_GENERIC     0
#define IPOQUE_PROTOCOL_LINE_SUBTYPE_AUDIO       1
#define IPOQUE_PROTOCOL_LINE_SUBTYPE_VIDEO       2
#define IPOQUE_PROTOCOL_LINE_SUBTYPE_STRING      "generic", "audio", "video"
#define IPOQUE_MAX_SUPPORTED_LINE_SUB_PROTOCOLS  2

/* NTLM subtypes */
#define IPOQUE_PROTOCOL_NTLM_SUBTYPE_PLAIN                        0
#define IPOQUE_PROTOCOL_NTLM_SUBTYPE_ENCRYPTED                    1
#define IPOQUE_PROTOCOL_NTLM_SUBTYPE_STRING    "plain", "encrypted"
#define IPOQUE_MAX_SUPPORTED_NTLM_SUB_PROTOCOLS                   1

/* WhatsApp subtypes */
#define IPOQUE_PROTOCOL_WHATSAPP_SUBTYPE_GENERIC                           0
#define IPOQUE_PROTOCOL_WHATSAPP_SUBTYPE_FILETRANSFER                      1
#define IPOQUE_PROTOCOL_WHATSAPP_SUBTYPE_VOICE_CALL                        2
#define IPOQUE_PROTOCOL_WHATSAPP_SUBTYPE_STRING "generic", "file-transfer", "voice-call"
#define IPOQUE_MAX_SUPPORTED_WHATSAPP_SUB_PROTOCOLS                        2

/* SMTP subtypes */
#define IPOQUE_PROTOCOL_SMTP_SUBTYPE_GENERIC        0
#define IPOQUE_PROTOCOL_SMTP_SUBTYPE_ENCRYPTED      1
#define IPOQUE_PROTOCOL_SMTP_SUBTYPE_STRING         "plain", "encrypted"
#define IPOQUE_MAX_SUPPORTED_SMTP_SUB_PROTOCOLS     1

/* IMAP subtypes */
#define IPOQUE_PROTOCOL_IMAP_SUBTYPE_GENERIC        0
#define IPOQUE_PROTOCOL_IMAP_SUBTYPE_ENCRYPTED      1
#define IPOQUE_PROTOCOL_IMAP_SUBTYPE_STRING         "plain", "encrypted"
#define IPOQUE_MAX_SUPPORTED_IMAP_SUB_PROTOCOLS     1

/* POP3 subtypes */
#define IPOQUE_PROTOCOL_POP3_SUBTYPE_GENERIC        0
#define IPOQUE_PROTOCOL_POP3_SUBTYPE_ENCRYPTED      1
#define IPOQUE_PROTOCOL_POP3_SUBTYPE_STRING         "plain", "encrypted"
#define IPOQUE_MAX_SUPPORTED_POP3_SUB_PROTOCOLS     1

/* LDAP subtypes */
#define IPOQUE_PROTOCOL_LDAP_SUBTYPE_GENERIC        0
#define IPOQUE_PROTOCOL_LDAP_SUBTYPE_ENCRYPTED      1
#define IPOQUE_PROTOCOL_LDAP_SUBTYPE_STRING         "plain", "encrypted"
#define IPOQUE_MAX_SUPPORTED_LDAP_SUB_PROTOCOLS     1

/* MQTT subtypes */
#define IPOQUE_PROTOCOL_MQTT_SUBTYPE_GENERIC        0
#define IPOQUE_PROTOCOL_MQTT_SUBTYPE_ENCRYPTED      1
#define IPOQUE_PROTOCOL_MQTT_SUBTYPE_STRING         "plain", "encrypted"
#define IPOQUE_MAX_SUPPORTED_MQTT_SUB_PROTOCOLS     1

/* Netflix subtypes */
#define IPOQUE_PROTOCOL_NETFLIX_SUBTYPE_GENERIC     0
#define IPOQUE_PROTOCOL_NETFLIX_SUBTYPE_VIDEO       1
#define IPOQUE_PROTOCOL_NETFLIX_SUBTYPE_STRING         "generic", "video"
#define IPOQUE_MAX_SUPPORTED_NETFLIX_SUB_PROTOCOLS     1

/* IEC61850 subtypes */
#define IPOQUE_PROTOCOL_IEC61850_SUBTYPE_GOOSE          0
#define IPOQUE_PROTOCOL_IEC61850_SUBTYPE_MMS            1
#define IPOQUE_PROTOCOL_IEC61850_SUBTYPE_SV             2
#define IPOQUE_PROTOCOL_IEC61850_SUBTYPE_STRING         "goose", "manufacturing-message", "sampled-values"
#define IPOQUE_MAX_SUPPORTED_IEC61850_SUB_PROTOCOLS     2

/* Supercell subtypes */
#define IPOQUE_PROTOCOL_SUPERCELL_SUBTYPE_GENERIC           0
#define IPOQUE_PROTOCOL_SUPERCELL_SUBTYPE_CLASH_OF_CLANS    1
#define IPOQUE_PROTOCOL_SUPERCELL_SUBTYPE_BOOM_BEACH        2
#define IPOQUE_PROTOCOL_SUPERCELL_SUBTYPE_HAY_DAY           3
#define IPOQUE_PROTOCOL_SUPERCELL_SUBTYPE_STRING            "generic", "clash-of-clans", "boom-beach", "hay-day"
#define IPOQUE_MAX_SUPPORTED_SUPERCELL_SUB_PROTOCOLS        3

/* Skype for Business subtypes */
#define IPOQUE_PROTOCOL_SKYPE_FOR_BUSINESS_SUBTYPE_GENERIC        0
#define IPOQUE_PROTOCOL_SKYPE_FOR_BUSINESS_SUBTYPE_AUDIO          1
#define IPOQUE_PROTOCOL_SKYPE_FOR_BUSINESS_SUBTYPE_VIDEO          2
#define IPOQUE_PROTOCOL_SKYPE_FOR_BUSINESS_SUBTYPE_FT             3
#define IPOQUE_MAX_SUPPORTED_SKYPE_FOR_BUSINESS_SUB_PROTOCOLS    3
#define IPOQUE_PROTOCOL_SKYPE_FOR_BUSINESS_SUBTYPE_STRING "generic","audio","video","filetransfer"

#ifdef IPOQUE_USE_PRX_PROTOCOLS_ONLY
#define IPOQUE_MAX_SUPPORTED_SUB_PROTOCOLS		11
#else
#define IPOQUE_MAX_SUPPORTED_SUB_PROTOCOLS		210
#endif

#ifdef __cplusplus
}
#endif
#endif
