/* written by Ralf Hoffmann, ipoque GmbH
 * ralf.hoffmann@ipoque.com
 */

#ifndef __IPOQUE_API_INCLUDE_FILE__
#error CANNOT INCLUDE THIS .H FILE, INCLUDE IPQ_API.H
#endif

#ifndef IPQ_PROTOCOLS_GROUPS_H
#define IPQ_PROTOCOLS_GROUPS_H

#ifdef __cplusplus
extern "C" {
#endif

	enum ipoque_protocol_groups {
		IPOQUE_GROUP_GENERIC = 0,
		IPOQUE_GROUP_STANDARD,
		IPOQUE_GROUP_P2P,
		IPOQUE_GROUP_GAMING,
		IPOQUE_GROUP_TUNNEL,
		IPOQUE_GROUP_BUSINESS,
		IPOQUE_GROUP_VOIP,
		IPOQUE_GROUP_IM,
		IPOQUE_GROUP_STREAMING,
		IPOQUE_GROUP_MOBILE,
		IPOQUE_GROUP_REMOTE_CONTROL,
		IPOQUE_GROUP_VIDEO,
		IPOQUE_GROUP_AUDIO,
		IPOQUE_GROUP_MAIL,
		IPOQUE_GROUP_NETWORK_MANAGEMENT,
		IPOQUE_GROUP_DATABASE,
		IPOQUE_GROUP_FILETRANSFER,
		IPOQUE_GROUP_WEB,
		IPOQUE_GROUP_CONFERENCE,
		IPOQUE_GROUP_SOCIAL_NETWORKING,
		IPOQUE_GROUP_ANTIVIRUS_UPDATE,

		IPOQUE_NUMBER_OF_GROUPS
	};

#ifdef __cplusplus
}
#endif

#endif
