/********************************************************************************/
/**
 ** \file       pace2_pa_grouping.h
 ** \brief      PACE 2 component programming interface of the grouping
 *              functionality for protocols and applications.
 ** \copyright  ipoque GmbH
 **/
/********************************************************************************/

#ifndef PACE2_PA_TAG_FUNC_H
#define PACE2_PA_TAG_FUNC_H

#include "pace2_basic_def.h"

#define PACE2_PA_TAGS_CUSTOM_COUNT  2048
#define PACE2_PA_TAGS_DEFAULT_COUNT 128

#define PACE2_PA_GET_MAIN_TAG_FAILURE 0xFFFF

#define PACE2_PA_INTERNAL_TAGS(X) \
        X(PACE2_PA_TAG_GENERIC = PACE2_PA_TAGS_CUSTOM_COUNT,    Generic)\
        X(PACE2_PA_TAG_P2P,                                     Peer to Peer)\
        X(PACE2_PA_TAG_GAMING,                                  Gaming)\
        X(PACE2_PA_TAG_TUNNEL,                                  Tunnel)\
        X(PACE2_PA_TAG_BUSINESS,                                Business)\
        X(PACE2_PA_TAG_E_COMMERCE,                              E-Commerce)\
        X(PACE2_PA_TAG_VOIP,                                    Voice over IP)\
        X(PACE2_PA_TAG_MESSAGING,                               Messaging)\
        X(PACE2_PA_TAG_STREAMING,                               Streaming)\
        X(PACE2_PA_TAG_MOBILE,                                  Mobile)\
        X(PACE2_PA_TAG_REMOTE_CONTROL,                          Remote Control)\
        X(PACE2_PA_TAG_MAIL,                                    Mail)\
        X(PACE2_PA_TAG_NETWORK_MANAGEMENT,                      Network Management)\
        X(PACE2_PA_TAG_DATABASE,                                Database)\
        X(PACE2_PA_TAG_FILETRANSFER,                            Filetransfer)\
        X(PACE2_PA_TAG_WEB,                                     Web)\
        X(PACE2_PA_TAG_CONFERENCE,                              Conference)\
        X(PACE2_PA_TAG_SOCIAL,                                  Social)\
        X(PACE2_PA_TAG_SHAREHOSTING,                            Sharehosting)

enum PACE2_pa_internal_tags {
    PACE2_PA_INTERNAL_TAGS(GENERATE_ENUM)
};

#define PACE2_PA_DEFAULT_PROTOCOL_TAGS(X) \
        X(PACE2_PROTOCOL_UNKNOWN,                       PACE2_PA_TAG_GENERIC)\
        X(PACE2_PROTOCOL_BITTORRENT,                    PACE2_PA_TAG_P2P)\
        X(PACE2_PROTOCOL_EDONKEY,                       PACE2_PA_TAG_P2P)\
        X(PACE2_PROTOCOL_GNUTELLA,                      PACE2_PA_TAG_P2P)\
        X(PACE2_PROTOCOL_WINMX,                         PACE2_PA_TAG_P2P)\
        X(PACE2_PROTOCOL_DIRECTCONNECT,                 PACE2_PA_TAG_P2P)\
        X(PACE2_PROTOCOL_APPLEJUICE,                    PACE2_PA_TAG_P2P)\
        X(PACE2_PROTOCOL_SOULSEEK,                      PACE2_PA_TAG_P2P)\
        X(PACE2_PROTOCOL_ARES,                          PACE2_PA_TAG_P2P)\
        X(PACE2_PROTOCOL_FREENET,                       PACE2_PA_TAG_P2P)\
        X(PACE2_PROTOCOL_MUTE,                          PACE2_PA_TAG_P2P)\
        X(PACE2_PROTOCOL_XDCC,                          PACE2_PA_TAG_MESSAGING)\
        X(PACE2_PROTOCOL_SKYPE,                         PACE2_PA_TAG_VOIP)\
        X(PACE2_PROTOCOL_SIP,                           PACE2_PA_TAG_VOIP)\
        X(PACE2_PROTOCOL_MSN,                           PACE2_PA_TAG_MESSAGING)\
        X(PACE2_PROTOCOL_YAHOO,                         PACE2_PA_TAG_MESSAGING)\
        X(PACE2_PROTOCOL_OSCAR,                         PACE2_PA_TAG_MESSAGING)\
        X(PACE2_PROTOCOL_IRC,                           PACE2_PA_TAG_MESSAGING)\
        X(PACE2_PROTOCOL_XMPP,                          PACE2_PA_TAG_MESSAGING)\
        X(PACE2_PROTOCOL_HTTP,                          PACE2_PA_TAG_WEB)\
        X(PACE2_PROTOCOL_POP,                           PACE2_PA_TAG_MAIL)\
        X(PACE2_PROTOCOL_SMTP,                          PACE2_PA_TAG_MAIL)\
        X(PACE2_PROTOCOL_IMAP,                          PACE2_PA_TAG_MAIL)\
        X(PACE2_PROTOCOL_USENET,                        PACE2_PA_TAG_MESSAGING)\
        X(PACE2_PROTOCOL_FTP,                           PACE2_PA_TAG_FILETRANSFER)\
        X(PACE2_PROTOCOL_DNS,                           PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_RTSP,                          PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_FILETOPIA,                     PACE2_PA_TAG_P2P)\
        X(PACE2_PROTOCOL_MANOLITO,                      PACE2_PA_TAG_P2P)\
        X(PACE2_PROTOCOL_IMESH,                         PACE2_PA_TAG_P2P)\
        X(PACE2_PROTOCOL_SSL,                           PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_FLASH,                         PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_MMS,                           PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_MPEG,                          PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_QUICKTIME,                     PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_PANDO,                         PACE2_PA_TAG_P2P)\
        X(PACE2_PROTOCOL_OPENVPN,                       PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_IPSEC,                         PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_GRE,                           PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_NOT_DETECTED,                  PACE2_PA_TAG_GENERIC)\
        X(PACE2_PROTOCOL_H323,                          PACE2_PA_TAG_VOIP)\
        X(PACE2_PROTOCOL_WINDOWSMEDIA,                  PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_REALMEDIA,                     PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_TVANTS,                        PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_SOPCAST,                       PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_TVUPLAYER,                     PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_PPSTREAM,                      PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_PPLIVE,                        PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_IAX,                           PACE2_PA_TAG_VOIP)\
        X(PACE2_PROTOCOL_VTUN,                          PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_MGCP,                          PACE2_PA_TAG_VOIP)\
        X(PACE2_PROTOCOL_GADUGADU,                      PACE2_PA_TAG_MESSAGING)\
        X(PACE2_PROTOCOL_ZATTOO,                        PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_WINNY,                         PACE2_PA_TAG_P2P)\
        X(PACE2_PROTOCOL_QQ,                            PACE2_PA_TAG_MESSAGING)\
        X(PACE2_PROTOCOL_QQLIVE,                        PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_FEIDIAN,                       PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_SSH,                           PACE2_PA_TAG_REMOTE_CONTROL)\
        X(PACE2_PROTOCOL_POPO,                          PACE2_PA_TAG_MESSAGING)\
        X(PACE2_PROTOCOL_THUNDER,                       PACE2_PA_TAG_P2P)\
        X(PACE2_PROTOCOL_UUSEE,                         PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_VNC,                           PACE2_PA_TAG_REMOTE_CONTROL)\
        X(PACE2_PROTOCOL_ICMP,                          PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_DHCP,                          PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_IGMP,                          PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_EGP,                           PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_STEAM,                         PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_HALFLIFE2,                     PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_XBOX,                          PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_SOFTETHER,                     PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_SCTP,                          PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_SMB,                           PACE2_PA_TAG_FILETRANSFER)\
        X(PACE2_PROTOCOL_TELNET,                        PACE2_PA_TAG_REMOTE_CONTROL)\
        X(PACE2_PROTOCOL_NTP,                           PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_NFS,                           PACE2_PA_TAG_FILETRANSFER)\
        X(PACE2_PROTOCOL_RTP,                           PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_TOR,                           PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_SSDP,                          PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_WORLDOFWARCRAFT,               PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_AVI,                           PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_VPN_X,                         PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_HAMACHI_VPN,                   PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_SKINNY,                        PACE2_PA_TAG_VOIP)\
        X(PACE2_PROTOCOL_CITRIX,                        PACE2_PA_TAG_BUSINESS)\
        X(PACE2_PROTOCOL_OGG,                           PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_PALTALK,                       PACE2_PA_TAG_MESSAGING)\
        X(PACE2_PROTOCOL_MOVE,                          PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_POSTGRES,                      PACE2_PA_TAG_DATABASE)\
        X(PACE2_PROTOCOL_OSPF,                          PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_BGP,                           PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_QUAKE,                         PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_SECONDLIFE,                    PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_MYSQL,                         PACE2_PA_TAG_DATABASE)\
        X(PACE2_PROTOCOL_BATTLEFIELD,                   PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_PCANYWHERE,                    PACE2_PA_TAG_REMOTE_CONTROL)\
        X(PACE2_PROTOCOL_RDP,                           PACE2_PA_TAG_REMOTE_CONTROL)\
        X(PACE2_PROTOCOL_SNMP,                          PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_KONTIKI,                       PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_VEOHTV,                        PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_KERBEROS,                      PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_IP_IN_IP,                      PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_GTP,                           PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_RADIUS,                        PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_STUN,                          PACE2_PA_TAG_VOIP)\
        X(PACE2_PROTOCOL_SYSLOG,                        PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_TDS,                           PACE2_PA_TAG_DATABASE)\
        X(PACE2_PROTOCOL_NETBIOS,                       PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_MDNS,                          PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_IPP,                           PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_LDAP,                          PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_WARCRAFT3,                     PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_XDMCP,                         PACE2_PA_TAG_REMOTE_CONTROL)\
        X(PACE2_PROTOCOL_OOVOO,                         PACE2_PA_TAG_CONFERENCE)\
        X(PACE2_PROTOCOL_FRING,                         PACE2_PA_TAG_VOIP)\
        X(PACE2_PROTOCOL_MAPI,                          PACE2_PA_TAG_MAIL)\
        X(PACE2_PROTOCOL_L2TP,                          PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_ISAKMP,                        PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_RTCP,                          PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_TFTP,                          PACE2_PA_TAG_FILETRANSFER)\
        X(PACE2_PROTOCOL_MSSQL,                         PACE2_PA_TAG_DATABASE)\
        X(PACE2_PROTOCOL_PPP,                           PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_PPTP,                          PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_STEALTHNET,                    PACE2_PA_TAG_P2P)\
        X(PACE2_PROTOCOL_SAP,                           PACE2_PA_TAG_BUSINESS)\
        X(PACE2_PROTOCOL_ICMPV6,                        PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_YOURFREEDOM,                   PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_VOIPSWITCH_VOIPTUNNEL,         PACE2_PA_TAG_VOIP)\
        X(PACE2_PROTOCOL_DHCPV6,                        PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_MEEBO,                         PACE2_PA_TAG_MESSAGING)\
        X(PACE2_PROTOCOL_FUNSHION,                      PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_AFP,                           PACE2_PA_TAG_FILETRANSFER)\
        X(PACE2_PROTOCOL_AIMINI,                        PACE2_PA_TAG_P2P)\
        X(PACE2_PROTOCOL_CLUBPENGUIN,                   PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_FLORENSIA,                     PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_TEAMSPEAK,                     PACE2_PA_TAG_VOIP)\
        X(PACE2_PROTOCOL_MAPLESTORY,                    PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_OSH,                           PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_PS3,                           PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_DOFUS,                         PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_WII,                           PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_WORLD_OF_KUNG_FU,              PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_FIESTA,                        PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_SPLASHFIGHTER,                 PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_CROSSFIRE,                     PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_WAP_WSP,                       PACE2_PA_TAG_MOBILE)\
        X(PACE2_PROTOCOL_WAP_WTP_WSP,                   PACE2_PA_TAG_MOBILE)\
        X(PACE2_PROTOCOL_WAP_WTLS,                      PACE2_PA_TAG_MOBILE)\
        X(PACE2_PROTOCOL_MULTIMEDIA_MESSAGING,          PACE2_PA_TAG_MOBILE)\
        X(PACE2_PROTOCOL_GUILDWARS,                     PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_ARMAGETRON,                    PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_RIM_PROPRIETARY,               PACE2_PA_TAG_MOBILE)\
        X(PACE2_PROTOCOL_RFACTOR,                       PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_RDT,                           PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_TEAMVIEWER,                    PACE2_PA_TAG_REMOTE_CONTROL)\
        X(PACE2_PROTOCOL_GAMEKIT,                       PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_NETMOTION,                     PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_TEREDO,                        PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_SPOTIFY,                       PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_IMPLUS,                        PACE2_PA_TAG_MESSAGING)\
        X(PACE2_PROTOCOL_ULTRASURF,                     PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_VIBER,                         PACE2_PA_TAG_VOIP)\
        X(PACE2_PROTOCOL_TANGO,                         PACE2_PA_TAG_VOIP)\
        X(PACE2_PROTOCOL_IPLAYER,                       PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_JBK3K,                         PACE2_PA_TAG_BUSINESS)\
        X(PACE2_PROTOCOL_OPERAMINI,                     PACE2_PA_TAG_MOBILE)\
        X(PACE2_PROTOCOL_BOLT,                          PACE2_PA_TAG_MOBILE)\
        X(PACE2_PROTOCOL_SCYDO,                         PACE2_PA_TAG_VOIP)\
        X(PACE2_PROTOCOL_WHATSAPP,                      PACE2_PA_TAG_MESSAGING)\
        X(PACE2_PROTOCOL_WEBEX,                         PACE2_PA_TAG_CONFERENCE)\
        X(PACE2_PROTOCOL_MOJO,                          PACE2_PA_TAG_P2P)\
        X(PACE2_PROTOCOL_IMO,                           PACE2_PA_TAG_MESSAGING)\
        X(PACE2_PROTOCOL_CITRIX_GOTO,                   PACE2_PA_TAG_CONFERENCE)\
        X(PACE2_PROTOCOL_COMODOUNITE,                   PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_GOOBER,                        PACE2_PA_TAG_VOIP)\
        X(PACE2_PROTOCOL_VENTRILO,                      PACE2_PA_TAG_VOIP)\
        X(PACE2_PROTOCOL_MYPEOPLE,                      PACE2_PA_TAG_VOIP)\
        X(PACE2_PROTOCOL_WEBSOCKET,                     PACE2_PA_TAG_WEB)\
        X(PACE2_PROTOCOL_EBUDDY,                        PACE2_PA_TAG_MESSAGING)\
        X(PACE2_PROTOCOL_SSTP,                          PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_ADOBE_CONNECT,                 PACE2_PA_TAG_BUSINESS)\
        X(PACE2_PROTOCOL_JAP,                           PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_LDP,                           PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_WUALA,                         PACE2_PA_TAG_WEB)\
        X(PACE2_PROTOCOL_MSRP,                          PACE2_PA_TAG_MESSAGING)\
        X(PACE2_PROTOCOL_LYNC,                          PACE2_PA_TAG_BUSINESS)\
        X(PACE2_PROTOCOL_SOCKS,                         PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_AUDIOGALAXY,                   PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_MIG33,                         PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_RHAPSODY,                      PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_SUDAPHONE,                     PACE2_PA_TAG_VOIP)\
        X(PACE2_PROTOCOL_WEBQQ,                         PACE2_PA_TAG_WEB)\
        X(PACE2_PROTOCOL_PDPROXY,                       PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_SILVERLIGHT,                   PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_CYBERGHOST,                    PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_FIX,                           PACE2_PA_TAG_BUSINESS)\
        X(PACE2_PROTOCOL_ORACLE_DB,                     PACE2_PA_TAG_DATABASE)\
        X(PACE2_PROTOCOL_RSVP,                          PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_LOTUS_NOTES,                   PACE2_PA_TAG_CONFERENCE)\
        X(PACE2_PROTOCOL_POISON_IVY,                    PACE2_PA_TAG_REMOTE_CONTROL)\
        X(PACE2_PROTOCOL_NETFLOW,                       PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_WECHAT,                        PACE2_PA_TAG_MESSAGING)\
        X(PACE2_PROTOCOL_SOAP,                          PACE2_PA_TAG_REMOTE_CONTROL)\
        X(PACE2_PROTOCOL_KIK_MESSENGER,                 PACE2_PA_TAG_MESSAGING)\
        X(PACE2_PROTOCOL_MPLUS,                         PACE2_PA_TAG_MESSAGING)\
        X(PACE2_PROTOCOL_LINE,                          PACE2_PA_TAG_VOIP)\
        X(PACE2_PROTOCOL_IPERF,                         PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_DIAMETER,                      PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_HIKE_MESSENGER,                PACE2_PA_TAG_MESSAGING)\
        X(PACE2_PROTOCOL_MQTT,                          PACE2_PA_TAG_GENERIC)\
        X(PACE2_PROTOCOL_DCE_RPC,                       PACE2_PA_TAG_REMOTE_CONTROL)\
        X(PACE2_PROTOCOL_IDRIVE,                        PACE2_PA_TAG_FILETRANSFER)\
        X(PACE2_PROTOCOL_DOTA2,                         PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_QVOD,                          PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_MSEXCHANGE,                    PACE2_PA_TAG_BUSINESS)\
        X(PACE2_PROTOCOL_MSNAV,                         PACE2_PA_TAG_BUSINESS)\
        X(PACE2_PROTOCOL_TIBIA,                         PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_KAKAO,                         PACE2_PA_TAG_MESSAGING)\
        X(PACE2_PROTOCOL_DESTINY,                       PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_VYPR_VPN,                      PACE2_PA_TAG_TUNNEL)\
        X(PACE2_PROTOCOL_TACACS,                        PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_THREEMA,                       PACE2_PA_TAG_MESSAGING)\
        X(PACE2_PROTOCOL_NTLM,                          PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_TELEGRAM,                      PACE2_PA_TAG_MESSAGING)\
        X(PACE2_PROTOCOL_WHOIS,                         PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_LAYER3_IPV4,                   PACE2_PA_TAG_WEB)\
        X(PACE2_PROTOCOL_LAYER3_IPV6,                   PACE2_PA_TAG_WEB)\
        X(PACE2_PROTOCOL_LAYER4_TCP,                    PACE2_PA_TAG_WEB)\
        X(PACE2_PROTOCOL_LAYER4_UDP,                    PACE2_PA_TAG_WEB)\
        X(PACE2_PROTOCOL_RTMP,                          PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_NNTP,                          PACE2_PA_TAG_BUSINESS)\
        X(PACE2_PROTOCOL_FLUTE,                         PACE2_PA_TAG_FILETRANSFER)\
        X(PACE2_PROTOCOL_MEGACO,                        PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_TWITCH,                        PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_QUIC,                          PACE2_PA_TAG_BUSINESS)\
        X(PACE2_PROTOCOL_FUZE,                          PACE2_PA_TAG_BUSINESS)\
        X(PACE2_PROTOCOL_AOWE,                          PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_DOOOK,                         PACE2_PA_TAG_MESSAGING)\
        X(PACE2_PROTOCOL_SPEEDTEST,                     PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_PROTOCOL_IEC61850,                      PACE2_PA_TAG_REMOTE_CONTROL)\
        X(PACE2_PROTOCOL_SCADA,                         PACE2_PA_TAG_BUSINESS)\
        X(PACE2_PROTOCOL_SHOUTCAST,                     PACE2_PA_TAG_STREAMING)\
        X(PACE2_PROTOCOL_CASSANDRA_QUERY_LANGUAGE,      PACE2_PA_TAG_DATABASE)\
        X(PACE2_PROTOCOL_CASSANDRA_INTERNODE_COMMUNICATION, PACE2_PA_TAG_DATABASE)\
        X(PACE2_PROTOCOL_THRIFT,                        PACE2_PA_TAG_GENERIC)\
        X(PACE2_PROTOCOL_PLAYSTATION,                   PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_SUPERCELL,                     PACE2_PA_TAG_GAMING)\
        X(PACE2_PROTOCOL_SKYPE_FOR_BUSINESS,            PACE2_PA_TAG_BUSINESS)\
        X(PACE2_PROTOCOL_T3,                            PACE2_PA_TAG_NETWORK_MANAGEMENT)

#define PACE2_PA_DEFAULT_APPLICATION_TAGS(X)\
        X(PACE2_APPLICATION_UNKNOWN,                    PACE2_PA_TAG_GENERIC)\
        X(PACE2_APPLICATION_FACEBOOK,                   PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_MAGICJACK,                  PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_ITUNES,                     PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_MYSPACE,                    PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_FACETIME,                   PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_TRUPHONE,                   PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_TWITTER,                    PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_XBOX,                       PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_REALMEDIA,                  PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_GOOGLE_MAIL,                PACE2_PA_TAG_MAIL)\
        X(PACE2_APPLICATION_GOOBER,                     PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_ICLOUD,                     PACE2_PA_TAG_FILETRANSFER)\
        X(PACE2_APPLICATION_UBUNTUONE,                  PACE2_PA_TAG_FILETRANSFER)\
        X(PACE2_APPLICATION_DROPBOX,                    PACE2_PA_TAG_FILETRANSFER)\
        X(PACE2_APPLICATION_YUILOP,                     PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_IMESSAGE,                   PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_GOTOMYPC,                   PACE2_PA_TAG_REMOTE_CONTROL)\
        X(PACE2_APPLICATION_GOTOMEETING,                PACE2_PA_TAG_CONFERENCE)\
        X(PACE2_APPLICATION_WINDOWS_AZURE,              PACE2_PA_TAG_FILETRANSFER)\
        X(PACE2_APPLICATION_AMAZON_CLOUD,               PACE2_PA_TAG_WEB)\
        X(PACE2_APPLICATION_DAILYMOTION,                PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_DEEZER,                     PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_GROOVESHARK,                PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_SUDAPHONE,                  PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_OFFICE365,                  PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_CNTV,                       PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_SINATV,                     PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_YOUTUBE,                    PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_VOIP_SWITCH,                PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_ZYNGA,                      PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_CRIMECITY,                  PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_MODERNWAR,                  PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_VIPPIE,                     PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_BOX,                        PACE2_PA_TAG_FILETRANSFER)\
        X(PACE2_APPLICATION_SKYDRIVE,                   PACE2_PA_TAG_FILETRANSFER)\
        X(PACE2_APPLICATION_ADOBE_CREATIVE_CLOUD,       PACE2_PA_TAG_WEB)\
        X(PACE2_APPLICATION_LINKEDIN,                   PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_ORKUT,                      PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_HI5,                        PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_SORIBADA,                   PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_ZOHO_WORK_ONLINE,           PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_HOTMAIL,                    PACE2_PA_TAG_MAIL)\
        X(PACE2_APPLICATION_INSTAGRAM,                  PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_SUGARSYNC,                  PACE2_PA_TAG_FILETRANSFER)\
        X(PACE2_APPLICATION_WICKR,                      PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_TIGERTEXT,                  PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_VIBE,                       PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_ENLEGION,                   PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_VOXER,                      PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_LOVEFILM,                   PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_FRIENDSTER,                 PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_BURNER,                     PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_FLICKR,                     PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_LIVE_COM,                   PACE2_PA_TAG_WEB)\
        X(PACE2_APPLICATION_ICQ_WEBCHAT,                PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_REDTUBE,                    PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_EVERNOTE,                   PACE2_PA_TAG_WEB)\
        X(PACE2_APPLICATION_SPREED,                     PACE2_PA_TAG_CONFERENCE)\
        X(PACE2_APPLICATION_TEXTPLUS,                   PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_XVIDEOS,                    PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_SNAPCHAT,                   PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_YOUKU,                      PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_MYMUSIC_TW,                 PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_RENREN,                     PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_YELP,                       PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_AMAZON_SHOP,                PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_YOUPORN,                    PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_EBAY,                       PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_PORNHUB,                    PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_SPIDEROAK,                  PACE2_PA_TAG_FILETRANSFER)\
        X(PACE2_APPLICATION_ADRIVE,                     PACE2_PA_TAG_FILETRANSFER)\
        X(PACE2_APPLICATION_TUMBLR,                     PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_XING,                       PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_GOOGLE_PLAY_MUSIC,          PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_VIMEO,                      PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_SALESFORCE,                 PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_ITUNES_RADIO,               PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_SINA_WEIBO,                 PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_FORFONE,                    PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_LIVEJASMIN,                 PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_JINGDONG,                   PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_LASTFM,                     PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_IMS,                        PACE2_PA_TAG_MOBILE)\
        X(PACE2_APPLICATION_BAIDU,                      PACE2_PA_TAG_WEB)\
        X(PACE2_APPLICATION_TAOBAO,                     PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_WATCHEVER,                  PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_TTPOD,                      PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_360MOBILE,                  PACE2_PA_TAG_MOBILE)\
        X(PACE2_APPLICATION_PINTEREST,                  PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_VINE,                       PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_NET2PHONE,                  PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_FOURSQUARE,                 PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_ILIVE_TO,                   PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_MEGA,                       PACE2_PA_TAG_FILETRANSFER)\
        X(PACE2_APPLICATION_DOOOK,                      PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_VBULLETIN,                  PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_CLOUDME,                    PACE2_PA_TAG_FILETRANSFER)\
        X(PACE2_APPLICATION_YIKYAK,                     PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_REDMINE,                    PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_IHEART_RADIO,               PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_AVIRA_ANTIVIRUS,            PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_NORTON_ANTIVIRUS,           PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_KASPERSKY_ANTIVIRUS,        PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_AVG_ANTIVIRUS,              PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_SOUNDCLOUD,                 PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_RDIO,                       PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_AMAZON_PRIME_MUSIC,         PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_RUNKEEPER,                  PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_MYBOOK,                     PACE2_PA_TAG_WEB)\
        X(PACE2_APPLICATION_NIKEPLUS,                   PACE2_PA_TAG_MOBILE)\
        X(PACE2_APPLICATION_MAGV,                       PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_MAGV_KIDS,                  PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_DOTA_LEGEND,                PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_LETV,                       PACE2_PA_TAG_WEB)\
        X(PACE2_APPLICATION_MY_FITNESS_PAL,             PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_SOHU,                       PACE2_PA_TAG_WEB)\
        X(PACE2_APPLICATION_1KXUN,                      PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_TVBS,                       PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_XNXX,                       PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_CTITV,                      PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_ENDOMONDO,                  PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_TIMELY_TV,                  PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_WORKOUT_TRAINER,            PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_MAP_MY_RUN,                 PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_KING_OF_PIRATES,            PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_TUDOU,                      PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_BITTORRENT,                 PACE2_PA_TAG_P2P)\
        X(PACE2_APPLICATION_EDONKEY,                    PACE2_PA_TAG_P2P)\
        X(PACE2_APPLICATION_FASTTRACK,                  PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_GNUTELLA,                   PACE2_PA_TAG_P2P)\
        X(PACE2_APPLICATION_DIRECTCONNECT,              PACE2_PA_TAG_P2P)\
        X(PACE2_APPLICATION_APPLEJUICE,                 PACE2_PA_TAG_P2P)\
        X(PACE2_APPLICATION_SOULSEEK,                   PACE2_PA_TAG_P2P)\
        X(PACE2_APPLICATION_ARES,                       PACE2_PA_TAG_P2P)\
        X(PACE2_APPLICATION_FREENET,                    PACE2_PA_TAG_P2P)\
        X(PACE2_APPLICATION_MUTE,                       PACE2_PA_TAG_P2P)\
        X(PACE2_APPLICATION_SKYPE,                      PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_MSN,                        PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_YAHOO,                      PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_VONAGE,                     PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_OSCAR,                      PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_GADUGADU,                   PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_MPLUS,                      PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_IRC,                        PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_SLINGBOX,                   PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_VCAST,                      PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_DDL_4SHARED_COM,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_ADRIVE_COM,             PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_BADONGO_COM,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_BADONGO_NET,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_BESTSHARING_COM,        PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_BIGFILEZ_COM,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_CHINAMOFILE_COM,        PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_DATA_HU,                PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_DEPOSITFILES_COM,       PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_EASY_SHARE_COM,         PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FAST_LOAD_NET,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FAST_SHARE_COM,         PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILE_UPLOAD_NET,        PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILE_UPLOAD_TO,         PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILEARCHIV_RU,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILEBASE_TO,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILECLOUD_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILEFACTORY_COM,        PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILEFRONT_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILEHO_COM,             PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILEHOST_TV,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILEPOST_RU,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILER_NET,              PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILES_UPLOAD_COM,       PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILES_TO,               PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILESAFE_TO,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILESEND_NET,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILEUPYOURS_COM,        PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FTP2SHARE_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_GIGASIZE_COM,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_GIGESHARE_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_HOSTGGG_COM,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_HOTFILE_COM,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_IFOLDER_RU,             PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_KEEPMYFILE_COM,         PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_LETECKAPOSTA_CZ,        PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_LIVE_SHARE_COM,         PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_LIVEDEPOT_NET,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_LOAD_TO,                PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_MASSMIRROR_COM,         PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_MEDIAFIRE_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_MEGAROTIC_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_MEGASHARE_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_MEGASHARES_COM,         PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_MEGAUPLOAD_COM,         PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_MOFILE_COM,             PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_MOFILE_NET,             PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_MYTEMPDIR_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_NETLOAD_IN,             PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_ODSIEBIE_NAJLEPSZE_NET, PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_QUICKSHARING_COM,       PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_RAPIDSHARE_COM,         PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_RAPIDSHARE_DE,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_RAPIDUPLOAD_COM,        PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_SAVEFILE_COM,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_SENDMEFILE_COM,         PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_SENDSPACE_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_SHAREBASE_TO,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_SHAREBEE_COM,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_SHAREBIG_COM,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_SHAREBIGFILE_COM,       PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_SHAREBIGFLIE_COM,       PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_SIMPLEUPLOAD_NET,       PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_SPEEDSHARE_ORG,         PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_TURBOUPLOAD_COM,        PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_ULTRASHARE_DE,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_UP_FILE_COM,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_UPLOADED_TO,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_UPLOADING_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_UPLOADINGIT_COM,        PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_UPLOADPOWER_COM,        PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_UPLOADYOURFILES_DE,     PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_VIP_FILE_COM,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_WIIUPLOAD_NET,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_YOURFILEHOST_COM,       PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_YOURFILES_BIZ,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_YOUTUBE_COM,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_ZSHARE_NET,             PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_4SHARED_VN,             PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_MEGA_1280_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_MEGASHARE_VN,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILESERVE_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILESONIC_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_1_UPLOAD_TO,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_1FICHIER_COM,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_4FASTFILE_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_10UPLOAD_COM,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_1CLICKSHARE_NET,        PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILEDUDE_COM,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_ASIXFILES_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_BANASHARE_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_BIGGERUPLOAD_COM,       PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_BITSHARE_COM,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_CASH_FILE_NET,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_CRAMIT_IN,              PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_CZSHARE_COM,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_DATA_LOADING_COM,       PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_DATAPORT_CZ,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_DATEI_TO,               PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_DOWNUPLOAD_COM,         PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_EASYBYTEZ_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_EDISK_CZ,               PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_ENTERUPLOAD_COM,        PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_EUROSHARE_EU,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_EXTABIT_COM,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FASTFILESHARE_COM_AR,   PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FIK1_COM,               PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILE2UPLOAD_NET,        PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILEAPE_COM,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILEFLYER_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILEFROG_COM,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILEHOOK_COM,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILEOVER_NET,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILEPOST_COM,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILES_MAIL_RU,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILESHARE_IN_UA,        PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILESMONSTER_COM,       PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILEVO_COM,             PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILEZUP_COM,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FREAKSHARE_NET,         PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FSHARE_VN,              PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_GAIAFILE_COM,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_GIGAPETA_COM,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_GOTOUPLOAD_COM,         PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_HELLSHARE_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_HITFILE_NET,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_HULKSHARE_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_HYPERFILESHARE_COM,     PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_I_FILEZ_COM,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_IFILE_IT,               PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_KEWLSHARE_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_LETITBIT_NET,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_LOADFILES_IN,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_MEGAFREE_KZ,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_MEGARAPID_EU,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_MEGASHARE_VNN_VN,       PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_MIDUPLOAD_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_MULTISHARE_CZ,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_NETUPLOADED_COM,        PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_ORON_COM,               PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_PRZEKLEJ_PL,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_PUTSHARE_COM,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_QSHARE_COM,             PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_QUICKSHARE_CZ,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_RAPIDSHARK_PL,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_SCRIBD_COM,             PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_SHARE_ONLINE_BZ,        PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_SHARE_RAPID_CZ,         PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_SHRAGLE_COM,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_STORAGE_TO,             PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_TERAFILES_NET,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_TUNABOX_NET,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_TURBOBIT_NET,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_UGOTFILE_COM,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_ULOZ_TO,                PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_UNIBYTES_COM,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_UNLIMIT_CO_IL,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_UP_4SHARE_VN,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_UPLOAD_COM_UA,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_UPLOADBOX_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_UPLOADER_PL,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_UPLOADFLOOR_COM,        PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_UPLOADSTATION_COM,      PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_UPNITO_SK,              PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_USERSHARE_NET,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_VIDEOBB_COM,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_WUPLOAD_COM,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_X7_TO,                  PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_YUNFILE_TO,             PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_ZOMGUPLOAD_TO,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_ZIDDU_COM,              PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_1_UPLOAD_COM,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_1_CLICKSHARE_COM,       PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_123UPLOAD_PL,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_139PAN_COM,             PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_163PAN_COM,             PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_2SHARED_COM,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_4SHARE_WS,              PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_4US_TO,                 PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_ALLDRIVES_GE,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_ALLSHARES_GE,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_ANNONHOST_NET,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_BOOSTERKING_COM,        PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_COBRASHARE_SK,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_COOLSHARE_CZ,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_CROCKO_COM,             PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_CUM_COM,                PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_EYVX_COM,               PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILEARN_COM,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILEJUNGLE_COM,         PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILEMAZE_WS,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILESFLASH_COM,         PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FREESPACE_BY,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FSX_HU,                 PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_JAKFILE_COM,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_JUMBOFILES_COM,         PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_KICKLOAD_COM,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_MISSUPLOAD_COM,         PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_MOVREEL_COM,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_PLATINSHARE_COM,        PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_SANUPLOAD_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_SHAREFLARE_NET,         PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_U_115_COM,              PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_UPLOADC_COM,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_UPLOADKING_COM,         PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_UPTOBOX_COM,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILESTUBE_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_GAMEFRONT_COM,          PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_MEGAPORN_COM,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_FILESONIC_IN,           PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_DDL_TURBOBIT_RU,            PACE2_PA_TAG_SHAREHOSTING)\
        X(PACE2_APPLICATION_USENET,                     PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_FTP,                        PACE2_PA_TAG_FILETRANSFER)\
        X(PACE2_APPLICATION_FILETOPIA,                  PACE2_PA_TAG_P2P)\
        X(PACE2_APPLICATION_MANOLITO,                   PACE2_PA_TAG_P2P)\
        X(PACE2_APPLICATION_IMESH,                      PACE2_PA_TAG_P2P)\
        X(PACE2_APPLICATION_PANDO,                      PACE2_PA_TAG_P2P)\
        X(PACE2_APPLICATION_SOPCAST,                    PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_TVUPLAYER,                  PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_PPSTREAM,                   PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_PPLIVE,                     PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_ZATTOO,                     PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_QQ,                         PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_QQLIVE,                     PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_FEIDIAN,                    PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_POPO,                       PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_THUNDER,                    PACE2_PA_TAG_P2P)\
        X(PACE2_APPLICATION_UUSEE,                      PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_VNC,                        PACE2_PA_TAG_REMOTE_CONTROL)\
        X(PACE2_APPLICATION_STEAM,                      PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_HALFLIFE2,                  PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_SOFTETHER,                  PACE2_PA_TAG_TUNNEL)\
        X(PACE2_APPLICATION_TELNET,                     PACE2_PA_TAG_REMOTE_CONTROL)\
        X(PACE2_APPLICATION_OFF,                        PACE2_PA_TAG_P2P)\
        X(PACE2_APPLICATION_TOR,                        PACE2_PA_TAG_TUNNEL)\
        X(PACE2_APPLICATION_WORLDOFWARCRAFT,            PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_HAMACHI_VPN,                PACE2_PA_TAG_TUNNEL)\
        X(PACE2_APPLICATION_SKINNY,                     PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_CITRIX,                     PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_PALTALK,                    PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_QUAKE,                      PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_SECONDLIFE,                 PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_BATTLEFIELD,                PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_PCANYWHERE,                 PACE2_PA_TAG_REMOTE_CONTROL)\
        X(PACE2_APPLICATION_ICECAST,                    PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_SHOUTCAST,                  PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_QQGAME,                     PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_VEOHTV,                     PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_OPENFT,                     PACE2_PA_TAG_P2P)\
        X(PACE2_APPLICATION_PANDORA,                    PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_IPP,                        PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_APPLICATION_WARCRAFT3,                  PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_OOVOO,                      PACE2_PA_TAG_CONFERENCE)\
        X(PACE2_APPLICATION_GOOGLE_TALK,                PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_ISKOOT,                     PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_FRING,                      PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_IPTV,                       PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_YOURFREEDOM,                PACE2_PA_TAG_TUNNEL)\
        X(PACE2_APPLICATION_VOIPSWITCH_VOIPTUNNEL,      PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_MEEBO,                      PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_FUNSHION,                   PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_AIMINI,                     PACE2_PA_TAG_P2P)\
        X(PACE2_APPLICATION_CLUBPENGUIN,                PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_FLORENSIA,                  PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_TEAMSPEAK,                  PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_MAPLESTORY,                 PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_OSH,                        PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_PS3,                        PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_DOFUS,                      PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_FIESTA,                     PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_SPLASHFIGHTER,              PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_ACTIVESYNC,                 PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_JABBER_APPLICATION_NIMBUZZ, PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_CROSSFIRE,                  PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_WAP_WSP,                    PACE2_PA_TAG_MOBILE)\
        X(PACE2_APPLICATION_GUILDWARS,                  PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_ARMAGETRON,                 PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_RFACTOR,                    PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_TEAMVIEWER,                 PACE2_PA_TAG_REMOTE_CONTROL)\
        X(PACE2_APPLICATION_GAMEKIT,                    PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_ULTRABAC,                   PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_SPOTIFY,                    PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_IMPLUS,                     PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_ANTSP2P,                    PACE2_PA_TAG_P2P)\
        X(PACE2_APPLICATION_ULTRASURF,                  PACE2_PA_TAG_TUNNEL)\
        X(PACE2_APPLICATION_VIBER,                      PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_TANGO,                      PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_IPLAYER,                    PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_OPERAMINI,                  PACE2_PA_TAG_MOBILE)\
        X(PACE2_APPLICATION_BOLT,                       PACE2_PA_TAG_MOBILE)\
        X(PACE2_APPLICATION_SCYDO,                      PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_WHATSAPP,                   PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_WEBEX,                      PACE2_PA_TAG_CONFERENCE)\
        X(PACE2_APPLICATION_NETFLIX,                    PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_MOJO,                       PACE2_PA_TAG_P2P)\
        X(PACE2_APPLICATION_IMO,                        PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_CITRIX_GOTO,                PACE2_PA_TAG_CONFERENCE)\
        X(PACE2_APPLICATION_FICALL,                     PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_COMODOUNITE,                PACE2_PA_TAG_TUNNEL)\
        X(PACE2_APPLICATION_VENTRILO,                   PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_MYPEOPLE,                   PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_EBUDDY,                     PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_ADOBE_CONNECT,              PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_JAP,                        PACE2_PA_TAG_TUNNEL)\
        X(PACE2_APPLICATION_WUALA,                      PACE2_PA_TAG_WEB)\
        X(PACE2_APPLICATION_WEBDAV,                     PACE2_PA_TAG_FILETRANSFER)\
        X(PACE2_APPLICATION_LYNC,                       PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_AUDIOGALAXY,                PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_MIG33,                      PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_HTTP_TUNNEL,                PACE2_PA_TAG_TUNNEL)\
        X(PACE2_APPLICATION_RHAPSODY,                   PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_WEBQQ,                      PACE2_PA_TAG_WEB)\
        X(PACE2_APPLICATION_PDPROXY,                    PACE2_PA_TAG_TUNNEL)\
        X(PACE2_APPLICATION_CYBERGHOST,                 PACE2_PA_TAG_TUNNEL)\
        X(PACE2_APPLICATION_GOOGLE_CLOUD,               PACE2_PA_TAG_WEB)\
        X(PACE2_APPLICATION_GOOGLE_DRIVE,               PACE2_PA_TAG_FILETRANSFER)\
        X(PACE2_APPLICATION_GOOGLE_DOCS,                PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_GOOGLE_PLUS,                PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_ORACLE_DB,                  PACE2_PA_TAG_DATABASE)\
        X(PACE2_APPLICATION_ITV,                        PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_DEMAND5,                    PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_RSVP,                       PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_APPLICATION_CHANNEL_4OD,                PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_LOTUS_NOTES,                PACE2_PA_TAG_CONFERENCE)\
        X(PACE2_APPLICATION_POISON_IVY,                 PACE2_PA_TAG_REMOTE_CONTROL)\
        X(PACE2_APPLICATION_HIDRIVE,                    PACE2_PA_TAG_FILETRANSFER)\
        X(PACE2_APPLICATION_WECHAT,                     PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_MYVIDEO,                    PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_KIK_MESSENGER,              PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_LINE,                       PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_IPERF,                      PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_APPLICATION_OS_UPDATE,                  PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_APPLICATION_HIKE_MESSENGER,             PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_DIDI,                       PACE2_PA_TAG_VOIP)\
        X(PACE2_APPLICATION_IDRIVE,                     PACE2_PA_TAG_FILETRANSFER)\
        X(PACE2_APPLICATION_SPREECAST,                  PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_SIMFY,                      PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_DOTA2,                      PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_QVOD,                       PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_HULU,                       PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_MSEXCHANGE,                 PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_MSNAV,                      PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_FUZE,                       PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_KAKAOTALK,                  PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_DESTINY,                    PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_VYPR_VPN,                   PACE2_PA_TAG_TUNNEL)\
        X(PACE2_APPLICATION_THREEMA,                    PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_NTLM,                       PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_APPLICATION_TWITCH,                     PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_WOWZA,                      PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_RUNTASTIC,                  PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_TELEGRAM,                   PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_STREETVOICE,                PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_DUOKAN,                     PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_MEI_LU,                     PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_SKOUT,                      PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_PLAYTALES,                  PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_GAME_OF_WAR,                PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_FETNET,                     PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_FBS,                        PACE2_PA_TAG_WEB)\
        X(PACE2_APPLICATION_NATIONAL_BASEBALL,          PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_PINKFONG,                   PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_KOLLECT_BOOK,               PACE2_PA_TAG_WEB)\
        X(PACE2_APPLICATION_SPTG_TV,                    PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_CIAOMOBILE_HDTV,            PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_SKYKING,                    PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_MOVES,                      PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_PATH,                       PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_AOWE,                       PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_IWOW_SYSTEX,                PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_9KU,                        PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_NEXTTV,                     PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_SYNCPLICITY,                PACE2_PA_TAG_FILETRANSFER)\
        X(PACE2_APPLICATION_REALMA,                     PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_YUANTA_WEB,                 PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_HINET,                      PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_MYCARD,                     PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_KONO,                       PACE2_PA_TAG_SOCIAL)\
        X(PACE2_APPLICATION_SPEAKABOOS,                 PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_DUO_DUO,                    PACE2_PA_TAG_WEB)\
        X(PACE2_APPLICATION_WEALTH_GOD,                 PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_ILEADER,                    PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_THREE_BAMBOO,               PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_TAAZE,                      PACE2_PA_TAG_WEB)\
        X(PACE2_APPLICATION_AUDIKO,                     PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_PUBU_BOOKBUFFET,            PACE2_PA_TAG_WEB)\
        X(PACE2_APPLICATION_MITAKE,                     PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_HYREAD,                     PACE2_PA_TAG_WEB)\
        X(PACE2_APPLICATION_DISNEY_STORYTIME,           PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_QUALYS,                     PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_CONSTANT_CONTACT,           PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_RALLY,                      PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_MAGINE_TV,                  PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_INTRALINKS,                 PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_LIVEPERSON,                 PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_SPEEDTEST,                  PACE2_PA_TAG_NETWORK_MANAGEMENT)\
        X(PACE2_APPLICATION_BLUEJEANS,                  PACE2_PA_TAG_MESSAGING)\
        X(PACE2_APPLICATION_APPLE_MUSIC,                PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_NAVER,                      PACE2_PA_TAG_WEB)\
        X(PACE2_APPLICATION_BOOKING_COM,                PACE2_PA_TAG_WEB)\
        X(PACE2_APPLICATION_CNN,                        PACE2_PA_TAG_WEB)\
        X(PACE2_APPLICATION_PERISCOPE,                  PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_PAYEASY,                    PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_LINE_RANGERS,               PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_IOS_APP_STORE,              PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_MYVIDEO_TW,                 PACE2_PA_TAG_STREAMING)\
        X(PACE2_APPLICATION_KING_GAMING,                PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_CANDY_CRUSH,                PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_CANDY_CRUSH_SODA,           PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_BUBBLE_WITCH,               PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_FARM_HERO,                  PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_PLAYSTATION,                PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_GOOGLE_PLAY,                PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_SUPERCELL,                  PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_CLASH_OF_CLANS,             PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_BOOM_BEACH,                 PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_HAY_DAY,                    PACE2_PA_TAG_GAMING)\
        X(PACE2_APPLICATION_WINDOWS_STORE,              PACE2_PA_TAG_BUSINESS)\
        X(PACE2_APPLICATION_SKYPE_FOR_BUSINESS,         PACE2_PA_TAG_BUSINESS)

#define PACE2_PA_GENERATE_DEFAULT_TAG_ARRAY(pa, group)     group,

/**
 * @brief Sets the main tag of a specified protocol.
 *
 * @param[in] pace2_module                  Pointer to the pace 2 module.
 * @param[in] proto_id                      ID of the protocol.
 * @param[in] main_tag                      Tag to assign to the protocol.
 * @retval PACE2_SUCCESS                    @copydoc PACE2_return_state::PACE2_SUCCESS
 * @retval PACE2_PARAM_MISSING              @copydoc PACE2_return_state::PACE2_PARAM_MISSING
 * @retval PACE2_OUT_OF_MEMORY              @copydoc PACE2_return_state::PACE2_OUT_OF_MEMORY
 * @retval PACE2_INDEX_OUTSIDE_ARRAY_BOUNDS @copydoc PACE2_return_state::PACE2_INDEX_OUTSIDE_ARRAY_BOUNDS
 */
PACE2_return_state pace2_set_protocol_main_tag(PACE2_module * const pace2_module, PACE2_protocols const proto_id,
                                               u16 const main_tag);
/**
 * @brief Sets the main tag of a specified application.
 *
 * @param[in] pace2_module                  Pointer to the pace 2 module.
 * @param[in] app_id                        ID of the application.
 * @param[in] main_tag                      Tag to assign to the application.
 * @retval PACE2_SUCCESS                    @copydoc PACE2_return_state::PACE2_SUCCESS
 * @retval PACE2_PARAM_MISSING              @copydoc PACE2_return_state::PACE2_PARAM_MISSING
 * @retval PACE2_OUT_OF_MEMORY              @copydoc PACE2_return_state::PACE2_OUT_OF_MEMORY
 * @retval PACE2_INDEX_OUTSIDE_ARRAY_BOUNDS @copydoc PACE2_return_state::PACE2_INDEX_OUTSIDE_ARRAY_BOUNDS
 */
PACE2_return_state pace2_set_application_main_tag(PACE2_module * const pace2_module, PACE2_applications const app_id,
                                                  u16 const main_tag);

/**
 * @brief Returns the main tag of a specified protocol or 0xFFFF if something is wrong.
 *
 * @param[in] pace2_module                  Pointer to the pace 2 module.
 * @param[in] proto_id                      ID of the protocol.
 * @return                                  Main tag of the specified protocol or 0xFFFF for failure.
 */
u16 pace2_get_protocol_main_tag(PACE2_module * const pace2_module, PACE2_protocols const proto_id);

/**
 * @brief Returns the main tag of a specified application or 0xFFFF if something is wrong.
 *
 * @param[in] pace2_module                  Pointer to the pace 2 module.
 * @param[in] app_id                        ID of the application.
 * @return                                  the main tag of the specified application or 0xFFFF for failure.
 */
u16 pace2_get_application_main_tag(PACE2_module * const pace2_module, PACE2_applications const app_id);

/**
 * @brief Returns a string representation of a specified protocol's main tag.
 *
 * @param[in] pace2_module                  Pointer to the pace 2 module.
 * @param[in] proto_id                      ID of the protocol.
 * @return                                  a string representation of the specified protocol's main tag.
 */
const char * pace2_get_protocol_main_tag_string(PACE2_module * const pace2_module, PACE2_protocols const proto_id);

/**
 * @brief Returns a string representation of a specified application's main tag.
 *
 * @param[in] pace2_module                  Pointer to the pace 2 module.
 * @param[in] proto_id                      ID of the application.
 * @return                                  a string representation of the specified application's main tag.
 *                                          In case of invalid parameters NULL is returned, when no string is set for
 *                                          this ID this function returns an empty string.
 */
const char * pace2_get_application_main_tag_string(PACE2_module * const pace2_module, PACE2_applications const app_id);

/**
 * @brief Returns a string representation of a specified tag.
 *
 * @param[in] pace2_module                  Pointer to the pace 2 module.
 * @param[in] tag                           ID of the tag.
 * @return                                  a string representation of the specified tag.
 */
const char * pace2_get_pa_tag_string(PACE2_module * const pace2_module, u16 const tag);

/**
 * @brief Adds a tag to a specified protocol.
 *
 * @param[in] pace2_module                  Pointer to the pace 2 module.
 * @param[in] proto_id                      ID of the protocol.
 * @param[in] tag                           ID of the tag.
 * @retval PACE2_SUCCESS                    @copydoc PACE2_return_state::PACE2_SUCCESS
 * @retval PACE2_PARAM_MISSING              @copydoc PACE2_return_state::PACE2_PARAM_MISSING
 * @retval PACE2_INVALID_TAG                @copydoc PACE2_return_state::PACE2_INVALID_TAG
 * @retval PACE2_INDEX_OUTSIDE_ARRAY_BOUNDS @copydoc PACE2_return_state::PACE2_INDEX_OUTSIDE_ARRAY_BOUNDS
 *                                          The given proto_id is bigger than the amount of protcol IDs.
 */
PACE2_return_state pace2_add_protocol_tag(PACE2_module * const pace2_module, PACE2_protocols const proto_id,
                                          u16 const tag);

/**
 * @brief Adds a tag to a specified application.
 *
 * @param[in] pace2_module                  Pointer to the pace 2 module.
 * @param[in] app_id                        ID of the application.
 * @param[in] tag                           ID of the tag.
 * @retval PACE2_SUCCESS                    @copydoc PACE2_return_state::PACE2_SUCCESS
 * @retval PACE2_PARAM_MISSING              @copydoc PACE2_return_state::PACE2_PARAM_MISSING
 * @retval PACE2_INVALID_TAG                @copydoc PACE2_return_state::PACE2_INVALID_TAG
 * @retval PACE2_INDEX_OUTSIDE_ARRAY_BOUNDS @copydoc PACE2_return_state::PACE2_INDEX_OUTSIDE_ARRAY_BOUNDS
 *                                          The given app_id is bigger than the amount of application IDs.
 */
PACE2_return_state pace2_add_application_tag(PACE2_module * const pace2_module, PACE2_applications const app_id,
                                             u16 const tag);

/**
 * @brief Removes a tag from a specified protocol.
 *
 * @param[in] pace2_module                  Pointer to the pace 2 module.
 * @param[in] proto_id                      ID of the protocol.
 * @param[in] tag                           ID of the tag.
 * @retval PACE2_SUCCESS                    @copydoc PACE2_return_state::PACE2_SUCCESS
 * @retval PACE2_PARAM_MISSING              @copydoc PACE2_return_state::PACE2_PARAM_MISSING
 * @retval PACE2_INVALID_TAG                @copydoc PACE2_return_state::PACE2_INVALID_TAG
 * @retval PACE2_INDEX_OUTSIDE_ARRAY_BOUNDS @copydoc PACE2_return_state::PACE2_INDEX_OUTSIDE_ARRAY_BOUNDS
 *                                          The given proto_id is bigger than the amount of protcol IDs.
 */
PACE2_return_state pace2_remove_protocol_tag(PACE2_module * const pace2_module, PACE2_protocols const proto_id,
                                             u16 const tag);

/**
 * @brief Removes a tag from a specified application.
 *
 * @param[in] pace2_module                  Pointer to the pace 2 module.
 * @param[in] app_id                        ID of the application.
 * @param[in] tag                           ID of the tag.
 * @retval PACE2_SUCCESS                    @copydoc PACE2_return_state::PACE2_SUCCESS
 * @retval PACE2_PARAM_MISSING              @copydoc PACE2_return_state::PACE2_PARAM_MISSING
 * @retval PACE2_INVALID_TAG                @copydoc PACE2_return_state::PACE2_INVALID_TAG
 * @retval PACE2_INDEX_OUTSIDE_ARRAY_BOUNDS @copydoc PACE2_return_state::PACE2_INDEX_OUTSIDE_ARRAY_BOUNDS
 *                                          The given proto_id is bigger than the amount of application IDs.
 */
PACE2_return_state pace2_remove_application_tag(PACE2_module * const pace2_module, PACE2_applications const app_id,
                                                u16 const tag);
/**
 * @brief Clears all tags of a specified protocol.
 *
 * @param[in] pace2_module                  Pointer to the pace 2 module.
 * @param[in] proto_id                      ID of the protocol.
 * @retval PACE2_SUCCESS                    @copydoc PACE2_return_state::PACE2_SUCCESS
 * @retval PACE2_PARAM_MISSING              @copydoc PACE2_return_state::PACE2_PARAM_MISSING
 * @retval PACE2_INDEX_OUTSIDE_ARRAY_BOUNDS @copydoc PACE2_return_state::PACE2_INDEX_OUTSIDE_ARRAY_BOUNDS
 *                                          The given proto_id is bigger than the amount of protocol IDs.
 */
PACE2_return_state pace2_clear_protocol_tags(PACE2_module * const pace2_module, PACE2_protocols const proto_id);

/**
 * @brief Clears all tags of a specified application.
 *
 * @param[in] pace2_module                  Pointer to the pace 2 module.
 * @param[in] app_id                        ID of the application.
 * @retval PACE2_SUCCESS                    @copydoc PACE2_return_state::PACE2_SUCCESS
 * @retval PACE2_PARAM_MISSING              @copydoc PACE2_return_state::PACE2_PARAM_MISSING
 * @retval PACE2_INDEX_OUTSIDE_ARRAY_BOUNDS @copydoc PACE2_return_state::PACE2_INDEX_OUTSIDE_ARRAY_BOUNDS
 *                                          The given proto_id is bigger than the amount of application IDs.
 */
PACE2_return_state pace2_clear_application_tags(PACE2_module * const pace2_module, PACE2_applications const app_id);

/**
 * @brief Checks whether a specified protocol has a specific tag.
 *
 * @param[in] pace2_module                  Pointer to the pace 2 module.
 * @param[in] proto_id                      ID of the protocol.
 * @param[in] tag                           ID of the tag.
 * @return                                  1 if the tag is set for the protocol, otherwise 0.
 */
u8 pace2_protocol_has_tag(PACE2_module * const pace2_module, PACE2_protocols const proto_id, u16 const tag);

/**
 * @brief Checks whether a specified application has a specific tag.
 *
 * @param[in] pace2_module                  Pointer to the pace 2 module.
 * @param[in] app_id                        ID of the application.
 * @param[in] tag                           ID of the tag.
 * @return                                  1 if the tag is set for the application, otherwise 0.
 */
u8 pace2_application_has_tag(PACE2_module * const pace2_module, PACE2_applications const app_id, u16 const tag);

#endif // PACE2_PA_TAG_FUNC_H

/*********************************************************************************
 ** EOF
 ********************************************************************************/
