#!/usr/bin/env python  
import os 
import requests 
import datetime 
import time 

#get client name from environment variables passed in
#by PPP, should be used one from /etc/chap-secrets 
#
try: 
    clientname = os.environ["PEERNAME"] 
except: 
    exit() 

#get the IP address assigned to remote client 
#in our case, UE 
#it could use PPP_REMOTE as well 
try: 
    clientIP = os.environ["IPREMOTE"]
except: 
    exit()


with open("/var/log/muse.log", "a") as f: 
    ts = time.time() 
    st = datetime.datetime.fromtimestamp(ts).strftime('%Y-%m-%d %H:%M:%S')
    f.write("%s UE client '%s' connected as '%s' \n" % 
              (st, clientname, clientIP)) 
    # send REST request to MUSE orchestrator 
    
    # payload = {'key1': 'value1', 'key2': 'value2'}
    # r = requests.post("http://httpbin.org/post", data=payload)
    # print(r.text) 
    # if r.status_code == requests.codes.ok: 
    #    f.write("success in post requests")
    # else: 
    #    f.write("failure in post requests")
    #

#all done, bye 






#bash 
#echo "hello " >> /tmp/abc
#env >> /tmp/abc 

